/*********************************************************************
 *
 * This file is autogenerated by /u/taniuchi/s467/upexps/202002_s467/../../ucesb/lu_common/make_acc_auto_def.sh
 *
 * Editing is useless.
 *
 *********************************************************************
 *
 * Input file:    /u/taniuchi/s467/upexps/202002_s467/../../ucesb/acc_def/has_pthread_getname_np.h
 * Basename:      HAS_PTHREAD_GETNAME_NP
 * Compiler:      g++
 * Compiler args: -I. -DUNPACKERNAME=202002_s467 -DUNPACKER_IS_202002_s467 -I/u/taniuchi/s467/upexps/202002_s467/../../ucesb/file_input -I/u/taniuchi/s467/upexps/202002_s467/../../ucesb/file_input/lmd_struct -I/u/taniuchi/s467/upexps/202002_s467/../../ucesb/threading -I/u/taniuchi/s467/upexps/202002_s467/../../ucesb/lu_common -I/u/taniuchi/s467/upexps/202002_s467/../../ucesb/acc_def -ansi -Wall -W -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wwrite-strings -Wconversion -g -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_LIMIT_MACROS -DHAVE_TEE -Igen_202002_s467 -DGENDIR="gen_202002_s467" -DUSE_EXT_WRITER= -DUSING_EXT_WRITER= -DEXT_WRITER_PREFIX="/u/taniuchi/s467/upexps/202002_s467/../../ucesb/hbook/" -I/u/taniuchi/s467/upexps/202002_s467/../../ucesb/hbook -DUSE_CURSES=1 -I/u/taniuchi/s467/upexps/202002_s467/../../ucesb/watcher -DCONTROL_INCLUDE -I./../land_common -I/cvmfs/fairroot.gsi.de/fairsoft/jun19p1//include -std=c++11 -DHAVE_THREAD_LOCAL_STORAGE -pthread -DUSE_PTHREAD=1 -DHAVE_PTHREAD -DUSE_LMD_INPUT=1 -DUSE_LMD_OUTPUT_TCP -I/u/taniuchi/s467/upexps/202002_s467/../../ucesb/mapcalib
 *
 ********************************************************************/

#ifndef __AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__
#define __AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__

/*
 * Option: pthread_h
 * Option: notavail
 */
/*
 * -DACC_DEF_HAS_PTHREAD_GETNAME_NP_pthread_h

cc1: warning: command line option '-std=c++11' is valid for C++/ObjC++ but not for C

 * --> exit 0 (len 84)
 */
/*
 * -DACC_DEF_HAS_PTHREAD_GETNAME_NP_notavail

cc1: warning: command line option '-std=c++11' is valid for C++/ObjC++ but not for C

 * --> exit 0 (len 84)
 */

/********************************************************************/

#define ACC_DEF_HAS_PTHREAD_GETNAME_NP_pthread_h 1

/********************************************************************/

#endif/*__AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__*/
