#########################################################
# Specify the name of the target executable

TARGETS:=s412

#########################################################
# Include common Makefile

include ../makefile_common.mk
