#########################################################
# Specify the name of the target executable

TARGETS:=s406

#########################################################
# Include common Makefile

include ../makefile_common.mk
