#########################################################
# Specify the name of the target executable

TARGETS:=s295

#########################################################
# Include common Makefile

include ../makefile_common.mk
