#########################################################
# Specify the name of the target executable

TARGETS:=201911_eng2

#########################################################
# Include common Makefile

include ../makefile_common.mk
