#########################################################
# Specify the name of the target executable

TARGETS:=land

#########################################################
# Include common Makefile

include ../makefile_common.mk
