/** BEGIN_MIRROR_STRUCT ************************************************
 *
 * Mirror (1 to 1) structure.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_mirror_define.hh"

#ifndef USER_DEF_raw_event_TS
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TS)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(HI);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(HI);
  STRUCT_MIRROR_ITEM_CTRL(LO);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LO);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TS);
};
#endif//USER_DEF_raw_event_TS

#ifndef USER_DEF_raw_event_ADC_TS
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_ADC_TS)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(H);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(H);
  STRUCT_MIRROR_ITEM_CTRL(L);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(L);
  STRUCT_MIRROR_FCNS_DECL(raw_event_ADC_TS);
};
#endif//USER_DEF_raw_event_ADC_TS

#ifndef USER_DEF_raw_event_ADC_CH
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_ADC_CH)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(MAXE);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(MAXE__i0,,2);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(MAXE[2]);
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,3);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[3]);
  STRUCT_MIRROR_ITEM_CTRL(GATE);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(GATE__i0,,8);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(GATE[8]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_ADC_CH);
};
#endif//USER_DEF_raw_event_ADC_CH

#ifndef USER_DEF_raw_event_ADC
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_ADC)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(N);
  STRUCT_MIRROR_TYPE(DATA8) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(N);
  STRUCT_MIRROR_ITEM_CTRL(TS);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(TS__i0,,16);
  STRUCT_MIRROR_TYPE(raw_event_ADC_TS) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TS[16]);
  STRUCT_MIRROR_ITEM_CTRL(CH);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(CH__i0,,14);
  STRUCT_MIRROR_TYPE(raw_event_ADC_CH) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(CH[14]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_ADC);
};
#endif//USER_DEF_raw_event_ADC

#ifndef USER_DEF_raw_event_LABRL
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_LABRL)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T);
  STRUCT_MIRROR_ITEM_CTRL(S);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(S);
  STRUCT_MIRROR_FCNS_DECL(raw_event_LABRL);
};
#endif//USER_DEF_raw_event_LABRL

#ifndef USER_DEF_raw_event_LABR
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_LABR)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(S);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(S);
  STRUCT_MIRROR_FCNS_DECL(raw_event_LABR);
};
#endif//USER_DEF_raw_event_LABR

#ifndef USER_DEF_raw_event_HPGEL
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_HPGEL)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T);
  STRUCT_MIRROR_ITEM_CTRL(S);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(S);
  STRUCT_MIRROR_FCNS_DECL(raw_event_HPGEL);
};
#endif//USER_DEF_raw_event_HPGEL

#ifndef USER_DEF_raw_event_HPGE
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_HPGE)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(S);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(S);
  STRUCT_MIRROR_FCNS_DECL(raw_event_HPGE);
};
#endif//USER_DEF_raw_event_HPGE

#ifndef USER_DEF_raw_event_N
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_N)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T);
  STRUCT_MIRROR_ITEM_CTRL(S);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(S);
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_ITEM_CTRL(P);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(P);
  STRUCT_MIRROR_FCNS_DECL(raw_event_N);
};
#endif//USER_DEF_raw_event_N

#ifndef USER_DEF_raw_event
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event) : public STRUCT_MIRROR_BASE(raw_event_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_event_base);
  STRUCT_MIRROR_ITEM_CTRL(TS);
  STRUCT_MIRROR_TYPE(raw_event_TS) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TS);
  STRUCT_MIRROR_ITEM_CTRL(TPAT);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TPAT);
  STRUCT_MIRROR_ITEM_CTRL(TRIG);
  STRUCT_MIRROR_TYPE(DATA8) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TRIG);
  STRUCT_MIRROR_ITEM_CTRL(TRLORAW);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(TRLORAW__i0,,16);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TRLORAW[16]);
  STRUCT_MIRROR_ITEM_CTRL(TRLOBDT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(TRLOBDT__i0,,16);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TRLOBDT[16]);
  STRUCT_MIRROR_ITEM_CTRL(TRLOADT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(TRLOADT__i0,,16);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TRLOADT[16]);
  STRUCT_MIRROR_ITEM_CTRL(TRLOARD);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(TRLOARD__i0,,16);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TRLOARD[16]);
  STRUCT_MIRROR_ITEM_CTRL(ADC);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(ADC__i0,,3);
  STRUCT_MIRROR_TYPE(raw_event_ADC) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ADC[3]);
  STRUCT_MIRROR_ITEM_CTRL(TRIGT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(TRIGT__i0,,12);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TRIGT[12]);
  STRUCT_MIRROR_ITEM_CTRL(LABRL);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(LABRL__i0,,4);
  STRUCT_MIRROR_TYPE(raw_event_LABRL) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LABRL[4]);
  STRUCT_MIRROR_ITEM_CTRL(LABR);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(LABR__i0,,4);
  STRUCT_MIRROR_TYPE(raw_event_LABR) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LABR[4]);
  STRUCT_MIRROR_ITEM_CTRL(HPGEL);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(HPGEL__i0,,4);
  STRUCT_MIRROR_TYPE(raw_event_HPGEL) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(HPGEL[4]);
  STRUCT_MIRROR_ITEM_CTRL(HPGE);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(HPGE__i0,,4);
  STRUCT_MIRROR_TYPE(raw_event_HPGE) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(HPGE[4]);
  STRUCT_MIRROR_ITEM_CTRL(CRM);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(CRM__i0,,8);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(CRM[8]);
  STRUCT_MIRROR_ITEM_CTRL(N);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(N__i0,,8);
  STRUCT_MIRROR_TYPE(raw_event_N) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(N[8]);
  STRUCT_MIRROR_FCNS_DECL(raw_event);
};
#endif//USER_DEF_raw_event

#ifndef USER_DEF_raw_sticky
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_sticky) : public STRUCT_MIRROR_BASE(raw_sticky_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_sticky_base);
  STRUCT_MIRROR_FCNS_DECL(raw_sticky);
};
#endif//USER_DEF_raw_sticky

#include "gen/default_mirror_undef.hh"


/** END_MIRROR_STRUCT *************************************************/
