/** BEGIN_FUNCTION_CALL_PER_MEMBER *************************************
 *
 * Recursive function calls per member.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_fcncall_define.hh"

#ifndef USER_DEF_raw_event_TS
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TS)::FCNCALL_NAME(raw_event_TS)
{
  FCNCALL_INIT;
  // DATA32 HI;
  {
  FCNCALL_SUBNAME("HI");
  { FCNCALL_CALL_CTRL_WRAP(HI,HI.FCNCALL_CALL(HI)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 LO;
  {
  FCNCALL_SUBNAME("LO");
  { FCNCALL_CALL_CTRL_WRAP(LO,LO.FCNCALL_CALL(LO)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TS

#ifndef USER_DEF_raw_event_ADC_TS
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_ADC_TS)::FCNCALL_NAME(raw_event_ADC_TS)
{
  FCNCALL_INIT;
  // DATA32 H;
  {
  FCNCALL_SUBNAME("H");
  { FCNCALL_CALL_CTRL_WRAP(H,H.FCNCALL_CALL(H)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 L;
  {
  FCNCALL_SUBNAME("L");
  { FCNCALL_CALL_CTRL_WRAP(L,L.FCNCALL_CALL(L)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_ADC_TS

#ifndef USER_DEF_raw_event_ADC_CH
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_ADC_CH)::FCNCALL_NAME(raw_event_ADC_CH)
{
  FCNCALL_INIT;
  // DATA32 MAXE[2];
  {
  FCNCALL_SUBNAME("MAXE");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(MAXE__i0,,__i0,MAXE[__i0].FCNCALL_CALL(MAXE[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 T[3];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,3)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 GATE[8];
  {
  FCNCALL_SUBNAME("GATE");
  FCNCALL_FOR(__i0,8)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(GATE__i0,,__i0,GATE[__i0].FCNCALL_CALL(GATE[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_ADC_CH

#ifndef USER_DEF_raw_event_ADC
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_ADC)::FCNCALL_NAME(raw_event_ADC)
{
  FCNCALL_INIT;
  // DATA8 N;
  {
  FCNCALL_SUBNAME("N");
  { FCNCALL_CALL_CTRL_WRAP(N,N.FCNCALL_CALL(N)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_ADC_TS TS[16];
  {
  FCNCALL_SUBNAME("TS");
  FCNCALL_FOR(__i0,16)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(TS__i0,,__i0,TS[__i0].FCNCALL_CALL(TS[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_ADC_CH CH[14];
  {
  FCNCALL_SUBNAME("CH");
  FCNCALL_FOR(__i0,14)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(CH__i0,,__i0,CH[__i0].FCNCALL_CALL(CH[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_ADC

#ifndef USER_DEF_raw_event_LABRL
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_LABRL)::FCNCALL_NAME(raw_event_LABRL)
{
  FCNCALL_INIT;
  // DATA12 T;
  {
  FCNCALL_SUBNAME("T");
  { FCNCALL_CALL_CTRL_WRAP(T,T.FCNCALL_CALL(T)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 S;
  {
  FCNCALL_SUBNAME("S");
  { FCNCALL_CALL_CTRL_WRAP(S,S.FCNCALL_CALL(S)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_LABRL

#ifndef USER_DEF_raw_event_LABR
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_LABR)::FCNCALL_NAME(raw_event_LABR)
{
  FCNCALL_INIT;
  // DATA32 S;
  {
  FCNCALL_SUBNAME("S");
  { FCNCALL_CALL_CTRL_WRAP(S,S.FCNCALL_CALL(S)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_LABR

#ifndef USER_DEF_raw_event_HPGEL
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_HPGEL)::FCNCALL_NAME(raw_event_HPGEL)
{
  FCNCALL_INIT;
  // DATA12 T;
  {
  FCNCALL_SUBNAME("T");
  { FCNCALL_CALL_CTRL_WRAP(T,T.FCNCALL_CALL(T)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 S;
  {
  FCNCALL_SUBNAME("S");
  { FCNCALL_CALL_CTRL_WRAP(S,S.FCNCALL_CALL(S)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_HPGEL

#ifndef USER_DEF_raw_event_HPGE
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_HPGE)::FCNCALL_NAME(raw_event_HPGE)
{
  FCNCALL_INIT;
  // DATA32 S;
  {
  FCNCALL_SUBNAME("S");
  { FCNCALL_CALL_CTRL_WRAP(S,S.FCNCALL_CALL(S)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_HPGE

#ifndef USER_DEF_raw_event_N
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_N)::FCNCALL_NAME(raw_event_N)
{
  FCNCALL_INIT;
  // DATA12 T;
  {
  FCNCALL_SUBNAME("T");
  { FCNCALL_CALL_CTRL_WRAP(T,T.FCNCALL_CALL(T)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 S;
  {
  FCNCALL_SUBNAME("S");
  { FCNCALL_CALL_CTRL_WRAP(S,S.FCNCALL_CALL(S)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA16 E;
  {
  FCNCALL_SUBNAME("E");
  { FCNCALL_CALL_CTRL_WRAP(E,E.FCNCALL_CALL(E)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA16 P;
  {
  FCNCALL_SUBNAME("P");
  { FCNCALL_CALL_CTRL_WRAP(P,P.FCNCALL_CALL(P)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_N

#ifndef USER_DEF_raw_event
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event)::FCNCALL_NAME(raw_event)
{
  FCNCALL_INIT;
  FCNCALL_CALL_CTRL_WRAP(raw_event_base,FCNCALL_CLASS_NAME(raw_event_base)::FCNCALL_CALL_BASE());
  // raw_event_TS TS;
  {
  FCNCALL_SUBNAME("TS");
  { FCNCALL_CALL_CTRL_WRAP(TS,TS.FCNCALL_CALL(TS)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 TPAT;
  {
  FCNCALL_SUBNAME("TPAT");
  { FCNCALL_CALL_CTRL_WRAP(TPAT,TPAT.FCNCALL_CALL(TPAT)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA8 TRIG;
  {
  FCNCALL_SUBNAME("TRIG");
  { FCNCALL_CALL_CTRL_WRAP(TRIG,TRIG.FCNCALL_CALL(TRIG)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 TRLORAW[16];
  {
  FCNCALL_SUBNAME("TRLORAW");
  FCNCALL_FOR(__i0,16)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(TRLORAW__i0,,__i0,TRLORAW[__i0].FCNCALL_CALL(TRLORAW[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 TRLOBDT[16];
  {
  FCNCALL_SUBNAME("TRLOBDT");
  FCNCALL_FOR(__i0,16)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(TRLOBDT__i0,,__i0,TRLOBDT[__i0].FCNCALL_CALL(TRLOBDT[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 TRLOADT[16];
  {
  FCNCALL_SUBNAME("TRLOADT");
  FCNCALL_FOR(__i0,16)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(TRLOADT__i0,,__i0,TRLOADT[__i0].FCNCALL_CALL(TRLOADT[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 TRLOARD[16];
  {
  FCNCALL_SUBNAME("TRLOARD");
  FCNCALL_FOR(__i0,16)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(TRLOARD__i0,,__i0,TRLOARD[__i0].FCNCALL_CALL(TRLOARD[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_ADC ADC[3];
  {
  FCNCALL_SUBNAME("ADC");
  FCNCALL_FOR(__i0,3)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(ADC__i0,,__i0,ADC[__i0].FCNCALL_CALL(ADC[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA12 TRIGT[12];
  {
  FCNCALL_SUBNAME("TRIGT");
  FCNCALL_FOR(__i0,12)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(TRIGT__i0,,__i0,TRIGT[__i0].FCNCALL_CALL(TRIGT[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_LABRL LABRL[4];
  {
  FCNCALL_SUBNAME("LABRL");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(LABRL__i0,,__i0,LABRL[__i0].FCNCALL_CALL(LABRL[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_LABR LABR[4];
  {
  FCNCALL_SUBNAME("LABR");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(LABR__i0,,__i0,LABR[__i0].FCNCALL_CALL(LABR[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_HPGEL HPGEL[4];
  {
  FCNCALL_SUBNAME("HPGEL");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(HPGEL__i0,,__i0,HPGEL[__i0].FCNCALL_CALL(HPGEL[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_HPGE HPGE[4];
  {
  FCNCALL_SUBNAME("HPGE");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(HPGE__i0,,__i0,HPGE[__i0].FCNCALL_CALL(HPGE[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 CRM[8];
  {
  FCNCALL_SUBNAME("CRM");
  FCNCALL_FOR(__i0,8)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(CRM__i0,,__i0,CRM[__i0].FCNCALL_CALL(CRM[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_N N[8];
  {
  FCNCALL_SUBNAME("N");
  FCNCALL_FOR(__i0,8)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(N__i0,,__i0,N[__i0].FCNCALL_CALL(N[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event

#ifndef USER_DEF_raw_sticky
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_sticky)::FCNCALL_NAME(raw_sticky)
{
  FCNCALL_INIT;
  FCNCALL_CALL_CTRL_WRAP(raw_sticky_base,FCNCALL_CLASS_NAME(raw_sticky_base)::FCNCALL_CALL_BASE());
  FCNCALL_RET;
}
#endif//USER_DEF_raw_sticky

#include "gen/default_fcncall_undef.hh"


/** END_FUNCTION_CALL_PER_MEMBER **************************************/
