#########################################################
# Specify the name of the target executable

TARGETS:=jun16 jun16C jun16U jun16Xe jun16_ptof

#########################################################
# Include common Makefile

include ../makefile_common.mk
