#########################################################
# Specify the name of the target executable(s)

TARGETS:=jun16 jun16_C jun16_U jun16_Xe jun16_ptof

#########################################################
# Include common Makefile

include ../makefile_common.mk
