#########################################################
# Specify the name of the target executable

TARGETS:=s393

#########################################################
# Include common Makefile

include ../makefile_common.mk
