#########################################################
# Specify the name of the target executable

TARGETS:=gamma3

#########################################################
# Include common Makefile

include ../makefile_common.mk
