#########################################################
# Specify the name of the target executable

TARGETS:=gamma3_1 gamma3_2

#########################################################
# Include common Makefile

include ../makefile_common.mk
