#########################################################
# Specify the name of the target executable

TARGETS:=s223_march

#########################################################
# Include common Makefile

include ../makefile_common.mk
