#########################################################
# Specify the name of the target executable

TARGETS:=califa

#########################################################
# Include common Makefile

include ../makefile_common.mk
