/** BEGIN_MIRROR_STRUCT ************************************************
 *
 * Mirror (1 to 1) structure.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_mirror_define.hh"

#ifndef USER_DEF_raw_event_TIMESTAMP_MASTER_WR
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_MASTER_WR)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,4);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[4]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_MASTER_WR);
};
#endif//USER_DEF_raw_event_TIMESTAMP_MASTER_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_MASTER
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_MASTER)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(ID);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ID);
  STRUCT_MIRROR_ITEM_CTRL(WR);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_MASTER_WR) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(WR);
  STRUCT_MIRROR_ITEM_CTRL(HI);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(HI);
  STRUCT_MIRROR_ITEM_CTRL(LO);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LO);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_MASTER);
};
#endif//USER_DEF_raw_event_TIMESTAMP_MASTER

#ifndef USER_DEF_raw_event_TIMESTAMP
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(MASTER);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_MASTER) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(MASTER);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP);
};
#endif//USER_DEF_raw_event_TIMESTAMP

#ifndef USER_DEF_raw_event_LOS
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_LOS)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(VTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,10> STRUCT_MIRROR_NAME(VTF);
  STRUCT_MIRROR_ITEM_CTRL(VTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),8,10> STRUCT_MIRROR_NAME(VTC);
  STRUCT_MIRROR_ITEM_CTRL(TTFL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,10> STRUCT_MIRROR_NAME(TTFL);
  STRUCT_MIRROR_ITEM_CTRL(TTFT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,10> STRUCT_MIRROR_NAME(TTFT);
  STRUCT_MIRROR_ITEM_CTRL(TTCL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,10> STRUCT_MIRROR_NAME(TTCL);
  STRUCT_MIRROR_ITEM_CTRL(TTCT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,10> STRUCT_MIRROR_NAME(TTCT);
  STRUCT_MIRROR_FCNS_DECL(raw_event_LOS);
};
#endif//USER_DEF_raw_event_LOS

#ifndef USER_DEF_raw_event_ROLU
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_ROLU)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(VTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,10> STRUCT_MIRROR_NAME(VTF);
  STRUCT_MIRROR_ITEM_CTRL(VTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),4,10> STRUCT_MIRROR_NAME(VTC);
  STRUCT_MIRROR_ITEM_CTRL(TTFL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,10> STRUCT_MIRROR_NAME(TTFL);
  STRUCT_MIRROR_ITEM_CTRL(TTFT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,10> STRUCT_MIRROR_NAME(TTFT);
  STRUCT_MIRROR_ITEM_CTRL(TTCL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,10> STRUCT_MIRROR_NAME(TTCL);
  STRUCT_MIRROR_ITEM_CTRL(TTCT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,10> STRUCT_MIRROR_NAME(TTCT);
  STRUCT_MIRROR_FCNS_DECL(raw_event_ROLU);
};
#endif//USER_DEF_raw_event_ROLU

#ifndef USER_DEF_raw_event_S
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_S)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(VTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,10> STRUCT_MIRROR_NAME(VTF);
  STRUCT_MIRROR_ITEM_CTRL(VTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),2,10> STRUCT_MIRROR_NAME(VTC);
  STRUCT_MIRROR_ITEM_CTRL(TTFL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,10> STRUCT_MIRROR_NAME(TTFL);
  STRUCT_MIRROR_ITEM_CTRL(TTFT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,10> STRUCT_MIRROR_NAME(TTFT);
  STRUCT_MIRROR_ITEM_CTRL(TTCL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,10> STRUCT_MIRROR_NAME(TTCL);
  STRUCT_MIRROR_ITEM_CTRL(TTCT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,10> STRUCT_MIRROR_NAME(TTCT);
  STRUCT_MIRROR_FCNS_DECL(raw_event_S);
};
#endif//USER_DEF_raw_event_S

#ifndef USER_DEF_raw_event_SST
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SST)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SST);
};
#endif//USER_DEF_raw_event_SST

#ifndef USER_DEF_raw_event_FIBTEN
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FIBTEN)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TMLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMLC);
  STRUCT_MIRROR_ITEM_CTRL(TMLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMLF);
  STRUCT_MIRROR_ITEM_CTRL(TMTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMTC);
  STRUCT_MIRROR_ITEM_CTRL(TMTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMTF);
  STRUCT_MIRROR_ITEM_CTRL(TSLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSLC);
  STRUCT_MIRROR_ITEM_CTRL(TSLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSLF);
  STRUCT_MIRROR_ITEM_CTRL(TSTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSTC);
  STRUCT_MIRROR_ITEM_CTRL(TSTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSTF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FIBTEN);
};
#endif//USER_DEF_raw_event_FIBTEN

#ifndef USER_DEF_raw_event_FIBELEVEN
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FIBELEVEN)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TMLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMLC);
  STRUCT_MIRROR_ITEM_CTRL(TMLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMLF);
  STRUCT_MIRROR_ITEM_CTRL(TMTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMTC);
  STRUCT_MIRROR_ITEM_CTRL(TMTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMTF);
  STRUCT_MIRROR_ITEM_CTRL(TSLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSLC);
  STRUCT_MIRROR_ITEM_CTRL(TSLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSLF);
  STRUCT_MIRROR_ITEM_CTRL(TSTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSTC);
  STRUCT_MIRROR_ITEM_CTRL(TSTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSTF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FIBELEVEN);
};
#endif//USER_DEF_raw_event_FIBELEVEN

#ifndef USER_DEF_raw_event_FIBTWELVE
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FIBTWELVE)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TMLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMLC);
  STRUCT_MIRROR_ITEM_CTRL(TMLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMLF);
  STRUCT_MIRROR_ITEM_CTRL(TMTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMTC);
  STRUCT_MIRROR_ITEM_CTRL(TMTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMTF);
  STRUCT_MIRROR_ITEM_CTRL(TSLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSLC);
  STRUCT_MIRROR_ITEM_CTRL(TSLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSLF);
  STRUCT_MIRROR_ITEM_CTRL(TSTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSTC);
  STRUCT_MIRROR_ITEM_CTRL(TSTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSTF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FIBTWELVE);
};
#endif//USER_DEF_raw_event_FIBTWELVE

#ifndef USER_DEF_raw_event_FIBTHIRTEEN
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FIBTHIRTEEN)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TMLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMLC);
  STRUCT_MIRROR_ITEM_CTRL(TMLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMLF);
  STRUCT_MIRROR_ITEM_CTRL(TMTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMTC);
  STRUCT_MIRROR_ITEM_CTRL(TMTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),512,64> STRUCT_MIRROR_NAME(TMTF);
  STRUCT_MIRROR_ITEM_CTRL(TSLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSLC);
  STRUCT_MIRROR_ITEM_CTRL(TSLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSLF);
  STRUCT_MIRROR_ITEM_CTRL(TSTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSTC);
  STRUCT_MIRROR_ITEM_CTRL(TSTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,64> STRUCT_MIRROR_NAME(TSTF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FIBTHIRTEEN);
};
#endif//USER_DEF_raw_event_FIBTHIRTEEN

#ifndef USER_DEF_raw_event_FIBTHREEA
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FIBTHREEA)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TMLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMLC);
  STRUCT_MIRROR_ITEM_CTRL(TMLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMLF);
  STRUCT_MIRROR_ITEM_CTRL(TMTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMTC);
  STRUCT_MIRROR_ITEM_CTRL(TMTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMTF);
  STRUCT_MIRROR_ITEM_CTRL(TSLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,64> STRUCT_MIRROR_NAME(TSLC);
  STRUCT_MIRROR_ITEM_CTRL(TSLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,64> STRUCT_MIRROR_NAME(TSLF);
  STRUCT_MIRROR_ITEM_CTRL(TSTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,64> STRUCT_MIRROR_NAME(TSTC);
  STRUCT_MIRROR_ITEM_CTRL(TSTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,64> STRUCT_MIRROR_NAME(TSTF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FIBTHREEA);
};
#endif//USER_DEF_raw_event_FIBTHREEA

#ifndef USER_DEF_raw_event_FIBTHREEB
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FIBTHREEB)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TMLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMLC);
  STRUCT_MIRROR_ITEM_CTRL(TMLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMLF);
  STRUCT_MIRROR_ITEM_CTRL(TMTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMTC);
  STRUCT_MIRROR_ITEM_CTRL(TMTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMTF);
  STRUCT_MIRROR_ITEM_CTRL(TSLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,64> STRUCT_MIRROR_NAME(TSLC);
  STRUCT_MIRROR_ITEM_CTRL(TSLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,64> STRUCT_MIRROR_NAME(TSLF);
  STRUCT_MIRROR_ITEM_CTRL(TSTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,64> STRUCT_MIRROR_NAME(TSTC);
  STRUCT_MIRROR_ITEM_CTRL(TSTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,64> STRUCT_MIRROR_NAME(TSTF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FIBTHREEB);
};
#endif//USER_DEF_raw_event_FIBTHREEB

#ifndef USER_DEF_raw_event_TOFD_P_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TOFD_P_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TFL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),48,64> STRUCT_MIRROR_NAME(TFL);
  STRUCT_MIRROR_ITEM_CTRL(TFT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),48,64> STRUCT_MIRROR_NAME(TFT);
  STRUCT_MIRROR_ITEM_CTRL(TCL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),48,64> STRUCT_MIRROR_NAME(TCL);
  STRUCT_MIRROR_ITEM_CTRL(TCT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),48,64> STRUCT_MIRROR_NAME(TCT);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TOFD_P_T);
};
#endif//USER_DEF_raw_event_TOFD_P_T

#ifndef USER_DEF_raw_event_TOFD_P
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TOFD_P)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_TOFD_P_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TOFD_P);
};
#endif//USER_DEF_raw_event_TOFD_P

#ifndef USER_DEF_raw_event_TOFD
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TOFD)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(P);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(P__i0,,4);
  STRUCT_MIRROR_TYPE(raw_event_TOFD_P) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(P[4]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TOFD);
};
#endif//USER_DEF_raw_event_TOFD

#ifndef USER_DEF_raw_event_CALIFA
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_CALIFA)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(ENE);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),6912> STRUCT_MIRROR_NAME(ENE);
  STRUCT_MIRROR_ITEM_CTRL(TSLSB);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),6912> STRUCT_MIRROR_NAME(TSLSB);
  STRUCT_MIRROR_ITEM_CTRL(TSMSB);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),6912> STRUCT_MIRROR_NAME(TSMSB);
  STRUCT_MIRROR_ITEM_CTRL(NF);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),6912> STRUCT_MIRROR_NAME(NF);
  STRUCT_MIRROR_ITEM_CTRL(NS);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),6912> STRUCT_MIRROR_NAME(NS);
  STRUCT_MIRROR_FCNS_DECL(raw_event_CALIFA);
};
#endif//USER_DEF_raw_event_CALIFA

#ifndef USER_DEF_raw_event_NN_P_tcl_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tcl_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(B);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),50,200> STRUCT_MIRROR_NAME(B);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tcl_T);
};
#endif//USER_DEF_raw_event_NN_P_tcl_T

#ifndef USER_DEF_raw_event_NN_P_tcl
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tcl)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tcl_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tcl);
};
#endif//USER_DEF_raw_event_NN_P_tcl

#ifndef USER_DEF_raw_event_NN_P_tfl_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tfl_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(B);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),50,200> STRUCT_MIRROR_NAME(B);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tfl_T);
};
#endif//USER_DEF_raw_event_NN_P_tfl_T

#ifndef USER_DEF_raw_event_NN_P_tfl
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tfl)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tfl_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tfl);
};
#endif//USER_DEF_raw_event_NN_P_tfl

#ifndef USER_DEF_raw_event_NN_P_tct_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tct_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(B);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),50,200> STRUCT_MIRROR_NAME(B);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tct_T);
};
#endif//USER_DEF_raw_event_NN_P_tct_T

#ifndef USER_DEF_raw_event_NN_P_tct
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tct)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tct_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tct);
};
#endif//USER_DEF_raw_event_NN_P_tct

#ifndef USER_DEF_raw_event_NN_P_tft_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tft_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(B);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),50,200> STRUCT_MIRROR_NAME(B);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tft_T);
};
#endif//USER_DEF_raw_event_NN_P_tft_T

#ifndef USER_DEF_raw_event_NN_P_tft
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tft)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tft_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tft);
};
#endif//USER_DEF_raw_event_NN_P_tft

#ifndef USER_DEF_raw_event_NN_P
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(tcl);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tcl) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tcl);
  STRUCT_MIRROR_ITEM_CTRL(tfl);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tfl) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tfl);
  STRUCT_MIRROR_ITEM_CTRL(tct);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tct) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tct);
  STRUCT_MIRROR_ITEM_CTRL(tft);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tft) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tft);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P);
};
#endif//USER_DEF_raw_event_NN_P

#ifndef USER_DEF_raw_event_NN
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(P);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(P__i0,,16);
  STRUCT_MIRROR_TYPE(raw_event_NN_P) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(P[16]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN);
};
#endif//USER_DEF_raw_event_NN

#ifndef USER_DEF_raw_event
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event) : public STRUCT_MIRROR_BASE(raw_event_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_event_base);
  STRUCT_MIRROR_ITEM_CTRL(TPAT);
  STRUCT_MIRROR_TYPE(raw_list_ii_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),170> STRUCT_MIRROR_NAME(TPAT);
  STRUCT_MIRROR_ITEM_CTRL(SAMPLOSH);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),512> STRUCT_MIRROR_NAME(SAMPLOSH);
  STRUCT_MIRROR_ITEM_CTRL(SAMPLOSL);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),512> STRUCT_MIRROR_NAME(SAMPLOSL);
  STRUCT_MIRROR_ITEM_CTRL(SAMPMSH);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),512> STRUCT_MIRROR_NAME(SAMPMSH);
  STRUCT_MIRROR_ITEM_CTRL(SAMPMSL);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),512> STRUCT_MIRROR_NAME(SAMPMSL);
  STRUCT_MIRROR_ITEM_CTRL(TIMESTAMP);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TIMESTAMP);
  STRUCT_MIRROR_ITEM_CTRL(LOS);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(LOS__i0,,1);
  STRUCT_MIRROR_TYPE(raw_event_LOS) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LOS[1]);
  STRUCT_MIRROR_ITEM_CTRL(ROLU);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(ROLU__i0,,1);
  STRUCT_MIRROR_TYPE(raw_event_ROLU) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ROLU[1]);
  STRUCT_MIRROR_ITEM_CTRL(S);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(S__i0,,8);
  STRUCT_MIRROR_TYPE(raw_event_S) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(S[8]);
  STRUCT_MIRROR_ITEM_CTRL(SST);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(SST__i0,,4);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(raw_event_SST),STRUCT_MIRROR_TEMPLATE_ARG(raw_event_SST),1024> STRUCT_MIRROR_NAME(SST[4]);
  STRUCT_MIRROR_ITEM_CTRL(FIBTEN);
  STRUCT_MIRROR_TYPE(raw_event_FIBTEN) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FIBTEN);
  STRUCT_MIRROR_ITEM_CTRL(FIBELEVEN);
  STRUCT_MIRROR_TYPE(raw_event_FIBELEVEN) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FIBELEVEN);
  STRUCT_MIRROR_ITEM_CTRL(FIBTWELVE);
  STRUCT_MIRROR_TYPE(raw_event_FIBTWELVE) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FIBTWELVE);
  STRUCT_MIRROR_ITEM_CTRL(FIBTHIRTEEN);
  STRUCT_MIRROR_TYPE(raw_event_FIBTHIRTEEN) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FIBTHIRTEEN);
  STRUCT_MIRROR_ITEM_CTRL(FIBTHREEA);
  STRUCT_MIRROR_TYPE(raw_event_FIBTHREEA) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FIBTHREEA);
  STRUCT_MIRROR_ITEM_CTRL(FIBTHREEB);
  STRUCT_MIRROR_TYPE(raw_event_FIBTHREEB) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FIBTHREEB);
  STRUCT_MIRROR_ITEM_CTRL(TOFD);
  STRUCT_MIRROR_TYPE(raw_event_TOFD) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TOFD);
  STRUCT_MIRROR_ITEM_CTRL(CALIFA);
  STRUCT_MIRROR_TYPE(raw_event_CALIFA) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(CALIFA);
  STRUCT_MIRROR_ITEM_CTRL(PSPX);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(PSPX__i0,,6);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),128,20> STRUCT_MIRROR_NAME(PSPX[6]);
  STRUCT_MIRROR_ITEM_CTRL(NN);
  STRUCT_MIRROR_TYPE(raw_event_NN) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(NN);
  STRUCT_MIRROR_FCNS_DECL(raw_event);
};
#endif//USER_DEF_raw_event

#include "gen/default_mirror_undef.hh"


/** END_MIRROR_STRUCT *************************************************/
