/** BEGIN_FUNCTION_CALL_PER_MEMBER *************************************
 *
 * Recursive function calls per member.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_fcncall_define.hh"

#ifndef USER_DEF_raw_event_TIMESTAMP_MASTER_WR
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_MASTER_WR)::FCNCALL_NAME(raw_event_TIMESTAMP_MASTER_WR)
{
  FCNCALL_INIT;
  // DATA16 T[4];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_MASTER_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_MASTER
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_MASTER)::FCNCALL_NAME(raw_event_TIMESTAMP_MASTER)
{
  FCNCALL_INIT;
  // DATA12 ID;
  {
  FCNCALL_SUBNAME("ID");
  { FCNCALL_CALL_CTRL_WRAP(ID,ID.FCNCALL_CALL(ID)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_MASTER_WR WR;
  {
  FCNCALL_SUBNAME("WR");
  { FCNCALL_CALL_CTRL_WRAP(WR,WR.FCNCALL_CALL(WR)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 HI;
  {
  FCNCALL_SUBNAME("HI");
  { FCNCALL_CALL_CTRL_WRAP(HI,HI.FCNCALL_CALL(HI)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 LO;
  {
  FCNCALL_SUBNAME("LO");
  { FCNCALL_CALL_CTRL_WRAP(LO,LO.FCNCALL_CALL(LO)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_MASTER

#ifndef USER_DEF_raw_event_TIMESTAMP
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP)::FCNCALL_NAME(raw_event_TIMESTAMP)
{
  FCNCALL_INIT;
  // raw_event_TIMESTAMP_MASTER MASTER;
  {
  FCNCALL_SUBNAME("MASTER");
  { FCNCALL_CALL_CTRL_WRAP(MASTER,MASTER.FCNCALL_CALL(MASTER)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP

#ifndef USER_DEF_raw_event_LOS
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_LOS)::FCNCALL_NAME(raw_event_LOS)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,8,10> VTF;
  {
  FCNCALL_SUBNAME("VTF");
  { FCNCALL_CALL_CTRL_WRAP(VTF,VTF.FCNCALL_CALL(VTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16,DATA16,8,10> VTC;
  {
  FCNCALL_SUBNAME("VTC");
  { FCNCALL_CALL_CTRL_WRAP(VTC,VTC.FCNCALL_CALL(VTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,8,10> TTFL;
  {
  FCNCALL_SUBNAME("TTFL");
  { FCNCALL_CALL_CTRL_WRAP(TTFL,TTFL.FCNCALL_CALL(TTFL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,8,10> TTFT;
  {
  FCNCALL_SUBNAME("TTFT");
  { FCNCALL_CALL_CTRL_WRAP(TTFT,TTFT.FCNCALL_CALL(TTFT)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,8,10> TTCL;
  {
  FCNCALL_SUBNAME("TTCL");
  { FCNCALL_CALL_CTRL_WRAP(TTCL,TTCL.FCNCALL_CALL(TTCL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,8,10> TTCT;
  {
  FCNCALL_SUBNAME("TTCT");
  { FCNCALL_CALL_CTRL_WRAP(TTCT,TTCT.FCNCALL_CALL(TTCT)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_LOS

#ifndef USER_DEF_raw_event_ROLU
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_ROLU)::FCNCALL_NAME(raw_event_ROLU)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,10> VTF;
  {
  FCNCALL_SUBNAME("VTF");
  { FCNCALL_CALL_CTRL_WRAP(VTF,VTF.FCNCALL_CALL(VTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16,DATA16,4,10> VTC;
  {
  FCNCALL_SUBNAME("VTC");
  { FCNCALL_CALL_CTRL_WRAP(VTC,VTC.FCNCALL_CALL(VTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,10> TTFL;
  {
  FCNCALL_SUBNAME("TTFL");
  { FCNCALL_CALL_CTRL_WRAP(TTFL,TTFL.FCNCALL_CALL(TTFL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,10> TTFT;
  {
  FCNCALL_SUBNAME("TTFT");
  { FCNCALL_CALL_CTRL_WRAP(TTFT,TTFT.FCNCALL_CALL(TTFT)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,10> TTCL;
  {
  FCNCALL_SUBNAME("TTCL");
  { FCNCALL_CALL_CTRL_WRAP(TTCL,TTCL.FCNCALL_CALL(TTCL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,10> TTCT;
  {
  FCNCALL_SUBNAME("TTCT");
  { FCNCALL_CALL_CTRL_WRAP(TTCT,TTCT.FCNCALL_CALL(TTCT)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_ROLU

#ifndef USER_DEF_raw_event_S
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_S)::FCNCALL_NAME(raw_event_S)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,10> VTF;
  {
  FCNCALL_SUBNAME("VTF");
  { FCNCALL_CALL_CTRL_WRAP(VTF,VTF.FCNCALL_CALL(VTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16,DATA16,2,10> VTC;
  {
  FCNCALL_SUBNAME("VTC");
  { FCNCALL_CALL_CTRL_WRAP(VTC,VTC.FCNCALL_CALL(VTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,10> TTFL;
  {
  FCNCALL_SUBNAME("TTFL");
  { FCNCALL_CALL_CTRL_WRAP(TTFL,TTFL.FCNCALL_CALL(TTFL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,10> TTFT;
  {
  FCNCALL_SUBNAME("TTFT");
  { FCNCALL_CALL_CTRL_WRAP(TTFT,TTFT.FCNCALL_CALL(TTFT)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,10> TTCL;
  {
  FCNCALL_SUBNAME("TTCL");
  { FCNCALL_CALL_CTRL_WRAP(TTCL,TTCL.FCNCALL_CALL(TTCL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,10> TTCT;
  {
  FCNCALL_SUBNAME("TTCT");
  { FCNCALL_CALL_CTRL_WRAP(TTCT,TTCT.FCNCALL_CALL(TTCT)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_S

#ifndef USER_DEF_raw_event_SST
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SST)::FCNCALL_NAME(raw_event_SST)
{
  FCNCALL_INIT;
  // DATA12 E;
  {
  FCNCALL_SUBNAME("E");
  { FCNCALL_CALL_CTRL_WRAP(E,E.FCNCALL_CALL(E)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SST

#ifndef USER_DEF_raw_event_FIBTEN
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_FIBTEN)::FCNCALL_NAME(raw_event_FIBTEN)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMLC;
  {
  FCNCALL_SUBNAME("TMLC");
  { FCNCALL_CALL_CTRL_WRAP(TMLC,TMLC.FCNCALL_CALL(TMLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMLF;
  {
  FCNCALL_SUBNAME("TMLF");
  { FCNCALL_CALL_CTRL_WRAP(TMLF,TMLF.FCNCALL_CALL(TMLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMTC;
  {
  FCNCALL_SUBNAME("TMTC");
  { FCNCALL_CALL_CTRL_WRAP(TMTC,TMTC.FCNCALL_CALL(TMTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMTF;
  {
  FCNCALL_SUBNAME("TMTF");
  { FCNCALL_CALL_CTRL_WRAP(TMTF,TMTF.FCNCALL_CALL(TMTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSLC;
  {
  FCNCALL_SUBNAME("TSLC");
  { FCNCALL_CALL_CTRL_WRAP(TSLC,TSLC.FCNCALL_CALL(TSLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSLF;
  {
  FCNCALL_SUBNAME("TSLF");
  { FCNCALL_CALL_CTRL_WRAP(TSLF,TSLF.FCNCALL_CALL(TSLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSTC;
  {
  FCNCALL_SUBNAME("TSTC");
  { FCNCALL_CALL_CTRL_WRAP(TSTC,TSTC.FCNCALL_CALL(TSTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSTF;
  {
  FCNCALL_SUBNAME("TSTF");
  { FCNCALL_CALL_CTRL_WRAP(TSTF,TSTF.FCNCALL_CALL(TSTF)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_FIBTEN

#ifndef USER_DEF_raw_event_FIBELEVEN
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_FIBELEVEN)::FCNCALL_NAME(raw_event_FIBELEVEN)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMLC;
  {
  FCNCALL_SUBNAME("TMLC");
  { FCNCALL_CALL_CTRL_WRAP(TMLC,TMLC.FCNCALL_CALL(TMLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMLF;
  {
  FCNCALL_SUBNAME("TMLF");
  { FCNCALL_CALL_CTRL_WRAP(TMLF,TMLF.FCNCALL_CALL(TMLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMTC;
  {
  FCNCALL_SUBNAME("TMTC");
  { FCNCALL_CALL_CTRL_WRAP(TMTC,TMTC.FCNCALL_CALL(TMTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMTF;
  {
  FCNCALL_SUBNAME("TMTF");
  { FCNCALL_CALL_CTRL_WRAP(TMTF,TMTF.FCNCALL_CALL(TMTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSLC;
  {
  FCNCALL_SUBNAME("TSLC");
  { FCNCALL_CALL_CTRL_WRAP(TSLC,TSLC.FCNCALL_CALL(TSLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSLF;
  {
  FCNCALL_SUBNAME("TSLF");
  { FCNCALL_CALL_CTRL_WRAP(TSLF,TSLF.FCNCALL_CALL(TSLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSTC;
  {
  FCNCALL_SUBNAME("TSTC");
  { FCNCALL_CALL_CTRL_WRAP(TSTC,TSTC.FCNCALL_CALL(TSTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSTF;
  {
  FCNCALL_SUBNAME("TSTF");
  { FCNCALL_CALL_CTRL_WRAP(TSTF,TSTF.FCNCALL_CALL(TSTF)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_FIBELEVEN

#ifndef USER_DEF_raw_event_FIBTWELVE
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_FIBTWELVE)::FCNCALL_NAME(raw_event_FIBTWELVE)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMLC;
  {
  FCNCALL_SUBNAME("TMLC");
  { FCNCALL_CALL_CTRL_WRAP(TMLC,TMLC.FCNCALL_CALL(TMLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMLF;
  {
  FCNCALL_SUBNAME("TMLF");
  { FCNCALL_CALL_CTRL_WRAP(TMLF,TMLF.FCNCALL_CALL(TMLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMTC;
  {
  FCNCALL_SUBNAME("TMTC");
  { FCNCALL_CALL_CTRL_WRAP(TMTC,TMTC.FCNCALL_CALL(TMTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMTF;
  {
  FCNCALL_SUBNAME("TMTF");
  { FCNCALL_CALL_CTRL_WRAP(TMTF,TMTF.FCNCALL_CALL(TMTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSLC;
  {
  FCNCALL_SUBNAME("TSLC");
  { FCNCALL_CALL_CTRL_WRAP(TSLC,TSLC.FCNCALL_CALL(TSLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSLF;
  {
  FCNCALL_SUBNAME("TSLF");
  { FCNCALL_CALL_CTRL_WRAP(TSLF,TSLF.FCNCALL_CALL(TSLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSTC;
  {
  FCNCALL_SUBNAME("TSTC");
  { FCNCALL_CALL_CTRL_WRAP(TSTC,TSTC.FCNCALL_CALL(TSTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSTF;
  {
  FCNCALL_SUBNAME("TSTF");
  { FCNCALL_CALL_CTRL_WRAP(TSTF,TSTF.FCNCALL_CALL(TSTF)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_FIBTWELVE

#ifndef USER_DEF_raw_event_FIBTHIRTEEN
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_FIBTHIRTEEN)::FCNCALL_NAME(raw_event_FIBTHIRTEEN)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMLC;
  {
  FCNCALL_SUBNAME("TMLC");
  { FCNCALL_CALL_CTRL_WRAP(TMLC,TMLC.FCNCALL_CALL(TMLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMLF;
  {
  FCNCALL_SUBNAME("TMLF");
  { FCNCALL_CALL_CTRL_WRAP(TMLF,TMLF.FCNCALL_CALL(TMLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMTC;
  {
  FCNCALL_SUBNAME("TMTC");
  { FCNCALL_CALL_CTRL_WRAP(TMTC,TMTC.FCNCALL_CALL(TMTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,512,64> TMTF;
  {
  FCNCALL_SUBNAME("TMTF");
  { FCNCALL_CALL_CTRL_WRAP(TMTF,TMTF.FCNCALL_CALL(TMTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSLC;
  {
  FCNCALL_SUBNAME("TSLC");
  { FCNCALL_CALL_CTRL_WRAP(TSLC,TSLC.FCNCALL_CALL(TSLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSLF;
  {
  FCNCALL_SUBNAME("TSLF");
  { FCNCALL_CALL_CTRL_WRAP(TSLF,TSLF.FCNCALL_CALL(TSLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSTC;
  {
  FCNCALL_SUBNAME("TSTC");
  { FCNCALL_CALL_CTRL_WRAP(TSTC,TSTC.FCNCALL_CALL(TSTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,4,64> TSTF;
  {
  FCNCALL_SUBNAME("TSTF");
  { FCNCALL_CALL_CTRL_WRAP(TSTF,TSTF.FCNCALL_CALL(TSTF)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_FIBTHIRTEEN

#ifndef USER_DEF_raw_event_FIBTHREEA
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_FIBTHREEA)::FCNCALL_NAME(raw_event_FIBTHREEA)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,256,64> TMLC;
  {
  FCNCALL_SUBNAME("TMLC");
  { FCNCALL_CALL_CTRL_WRAP(TMLC,TMLC.FCNCALL_CALL(TMLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,256,64> TMLF;
  {
  FCNCALL_SUBNAME("TMLF");
  { FCNCALL_CALL_CTRL_WRAP(TMLF,TMLF.FCNCALL_CALL(TMLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,256,64> TMTC;
  {
  FCNCALL_SUBNAME("TMTC");
  { FCNCALL_CALL_CTRL_WRAP(TMTC,TMTC.FCNCALL_CALL(TMTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,256,64> TMTF;
  {
  FCNCALL_SUBNAME("TMTF");
  { FCNCALL_CALL_CTRL_WRAP(TMTF,TMTF.FCNCALL_CALL(TMTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,64> TSLC;
  {
  FCNCALL_SUBNAME("TSLC");
  { FCNCALL_CALL_CTRL_WRAP(TSLC,TSLC.FCNCALL_CALL(TSLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,64> TSLF;
  {
  FCNCALL_SUBNAME("TSLF");
  { FCNCALL_CALL_CTRL_WRAP(TSLF,TSLF.FCNCALL_CALL(TSLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,64> TSTC;
  {
  FCNCALL_SUBNAME("TSTC");
  { FCNCALL_CALL_CTRL_WRAP(TSTC,TSTC.FCNCALL_CALL(TSTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,64> TSTF;
  {
  FCNCALL_SUBNAME("TSTF");
  { FCNCALL_CALL_CTRL_WRAP(TSTF,TSTF.FCNCALL_CALL(TSTF)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_FIBTHREEA

#ifndef USER_DEF_raw_event_FIBTHREEB
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_FIBTHREEB)::FCNCALL_NAME(raw_event_FIBTHREEB)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,256,64> TMLC;
  {
  FCNCALL_SUBNAME("TMLC");
  { FCNCALL_CALL_CTRL_WRAP(TMLC,TMLC.FCNCALL_CALL(TMLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,256,64> TMLF;
  {
  FCNCALL_SUBNAME("TMLF");
  { FCNCALL_CALL_CTRL_WRAP(TMLF,TMLF.FCNCALL_CALL(TMLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,256,64> TMTC;
  {
  FCNCALL_SUBNAME("TMTC");
  { FCNCALL_CALL_CTRL_WRAP(TMTC,TMTC.FCNCALL_CALL(TMTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,256,64> TMTF;
  {
  FCNCALL_SUBNAME("TMTF");
  { FCNCALL_CALL_CTRL_WRAP(TMTF,TMTF.FCNCALL_CALL(TMTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,64> TSLC;
  {
  FCNCALL_SUBNAME("TSLC");
  { FCNCALL_CALL_CTRL_WRAP(TSLC,TSLC.FCNCALL_CALL(TSLC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,64> TSLF;
  {
  FCNCALL_SUBNAME("TSLF");
  { FCNCALL_CALL_CTRL_WRAP(TSLF,TSLF.FCNCALL_CALL(TSLF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,64> TSTC;
  {
  FCNCALL_SUBNAME("TSTC");
  { FCNCALL_CALL_CTRL_WRAP(TSTC,TSTC.FCNCALL_CALL(TSTC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,64> TSTF;
  {
  FCNCALL_SUBNAME("TSTF");
  { FCNCALL_CALL_CTRL_WRAP(TSTF,TSTF.FCNCALL_CALL(TSTF)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_FIBTHREEB

#ifndef USER_DEF_raw_event_TOFD_P_T
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TOFD_P_T)::FCNCALL_NAME(raw_event_TOFD_P_T)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,48,64> TFL;
  {
  FCNCALL_SUBNAME("TFL");
  { FCNCALL_CALL_CTRL_WRAP(TFL,TFL.FCNCALL_CALL(TFL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,48,64> TFT;
  {
  FCNCALL_SUBNAME("TFT");
  { FCNCALL_CALL_CTRL_WRAP(TFT,TFT.FCNCALL_CALL(TFT)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,48,64> TCL;
  {
  FCNCALL_SUBNAME("TCL");
  { FCNCALL_CALL_CTRL_WRAP(TCL,TCL.FCNCALL_CALL(TCL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA12,DATA12,48,64> TCT;
  {
  FCNCALL_SUBNAME("TCT");
  { FCNCALL_CALL_CTRL_WRAP(TCT,TCT.FCNCALL_CALL(TCT)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TOFD_P_T

#ifndef USER_DEF_raw_event_TOFD_P
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TOFD_P)::FCNCALL_NAME(raw_event_TOFD_P)
{
  FCNCALL_INIT;
  // raw_event_TOFD_P_T T[2];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TOFD_P

#ifndef USER_DEF_raw_event_TOFD
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TOFD)::FCNCALL_NAME(raw_event_TOFD)
{
  FCNCALL_INIT;
  // raw_event_TOFD_P P[4];
  {
  FCNCALL_SUBNAME("P");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(P__i0,,__i0,P[__i0].FCNCALL_CALL(P[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TOFD

#ifndef USER_DEF_raw_event_CALIFA
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_CALIFA)::FCNCALL_NAME(raw_event_CALIFA)
{
  FCNCALL_INIT;
  // raw_array_zero_suppress<DATA16,DATA16,6912> ENE;
  {
  FCNCALL_SUBNAME("ENE");
  { FCNCALL_CALL_CTRL_WRAP(ENE,ENE.FCNCALL_CALL(ENE)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA32,DATA32,6912> TSLSB;
  {
  FCNCALL_SUBNAME("TSLSB");
  { FCNCALL_CALL_CTRL_WRAP(TSLSB,TSLSB.FCNCALL_CALL(TSLSB)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA32,DATA32,6912> TSMSB;
  {
  FCNCALL_SUBNAME("TSMSB");
  { FCNCALL_CALL_CTRL_WRAP(TSMSB,TSMSB.FCNCALL_CALL(TSMSB)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA16,DATA16,6912> NF;
  {
  FCNCALL_SUBNAME("NF");
  { FCNCALL_CALL_CTRL_WRAP(NF,NF.FCNCALL_CALL(NF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA16,DATA16,6912> NS;
  {
  FCNCALL_SUBNAME("NS");
  { FCNCALL_CALL_CTRL_WRAP(NS,NS.FCNCALL_CALL(NS)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_CALIFA

#ifndef USER_DEF_raw_event_NN_P_tcl_T
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tcl_T)::FCNCALL_NAME(raw_event_NN_P_tcl_T)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,50,200> B;
  {
  FCNCALL_SUBNAME("B");
  { FCNCALL_CALL_CTRL_WRAP(B,B.FCNCALL_CALL(B)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tcl_T

#ifndef USER_DEF_raw_event_NN_P_tcl
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tcl)::FCNCALL_NAME(raw_event_NN_P_tcl)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tcl_T T[2];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tcl

#ifndef USER_DEF_raw_event_NN_P_tfl_T
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tfl_T)::FCNCALL_NAME(raw_event_NN_P_tfl_T)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,50,200> B;
  {
  FCNCALL_SUBNAME("B");
  { FCNCALL_CALL_CTRL_WRAP(B,B.FCNCALL_CALL(B)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tfl_T

#ifndef USER_DEF_raw_event_NN_P_tfl
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tfl)::FCNCALL_NAME(raw_event_NN_P_tfl)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tfl_T T[2];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tfl

#ifndef USER_DEF_raw_event_NN_P_tct_T
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tct_T)::FCNCALL_NAME(raw_event_NN_P_tct_T)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,50,200> B;
  {
  FCNCALL_SUBNAME("B");
  { FCNCALL_CALL_CTRL_WRAP(B,B.FCNCALL_CALL(B)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tct_T

#ifndef USER_DEF_raw_event_NN_P_tct
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tct)::FCNCALL_NAME(raw_event_NN_P_tct)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tct_T T[2];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tct

#ifndef USER_DEF_raw_event_NN_P_tft_T
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tft_T)::FCNCALL_NAME(raw_event_NN_P_tft_T)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,50,200> B;
  {
  FCNCALL_SUBNAME("B");
  { FCNCALL_CALL_CTRL_WRAP(B,B.FCNCALL_CALL(B)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tft_T

#ifndef USER_DEF_raw_event_NN_P_tft
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tft)::FCNCALL_NAME(raw_event_NN_P_tft)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tft_T T[2];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tft

#ifndef USER_DEF_raw_event_NN_P
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P)::FCNCALL_NAME(raw_event_NN_P)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tcl tcl;
  {
  FCNCALL_SUBNAME("tcl");
  { FCNCALL_CALL_CTRL_WRAP(tcl,tcl.FCNCALL_CALL(tcl)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_NN_P_tfl tfl;
  {
  FCNCALL_SUBNAME("tfl");
  { FCNCALL_CALL_CTRL_WRAP(tfl,tfl.FCNCALL_CALL(tfl)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_NN_P_tct tct;
  {
  FCNCALL_SUBNAME("tct");
  { FCNCALL_CALL_CTRL_WRAP(tct,tct.FCNCALL_CALL(tct)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_NN_P_tft tft;
  {
  FCNCALL_SUBNAME("tft");
  { FCNCALL_CALL_CTRL_WRAP(tft,tft.FCNCALL_CALL(tft)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P

#ifndef USER_DEF_raw_event_NN
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN)::FCNCALL_NAME(raw_event_NN)
{
  FCNCALL_INIT;
  // raw_event_NN_P P[16];
  {
  FCNCALL_SUBNAME("P");
  FCNCALL_FOR(__i0,16)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(P__i0,,__i0,P[__i0].FCNCALL_CALL(P[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN

#ifndef USER_DEF_raw_event
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event)::FCNCALL_NAME(raw_event)
{
  FCNCALL_INIT;
  FCNCALL_CALL_CTRL_WRAP(raw_event_base,FCNCALL_CLASS_NAME(raw_event_base)::FCNCALL_CALL_BASE());
  // raw_list_ii_zero_suppress<DATA16,DATA16,170> TPAT;
  {
  FCNCALL_SUBNAME("TPAT");
  { FCNCALL_CALL_CTRL_WRAP(TPAT,TPAT.FCNCALL_CALL(TPAT)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA32,DATA32,512> SAMPLOSH;
  {
  FCNCALL_SUBNAME("SAMPLOSH");
  { FCNCALL_CALL_CTRL_WRAP(SAMPLOSH,SAMPLOSH.FCNCALL_CALL(SAMPLOSH)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA32,DATA32,512> SAMPLOSL;
  {
  FCNCALL_SUBNAME("SAMPLOSL");
  { FCNCALL_CALL_CTRL_WRAP(SAMPLOSL,SAMPLOSL.FCNCALL_CALL(SAMPLOSL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA32,DATA32,512> SAMPMSH;
  {
  FCNCALL_SUBNAME("SAMPMSH");
  { FCNCALL_CALL_CTRL_WRAP(SAMPMSH,SAMPMSH.FCNCALL_CALL(SAMPMSH)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA32,DATA32,512> SAMPMSL;
  {
  FCNCALL_SUBNAME("SAMPMSL");
  { FCNCALL_CALL_CTRL_WRAP(SAMPMSL,SAMPMSL.FCNCALL_CALL(SAMPMSL)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP TIMESTAMP;
  {
  FCNCALL_SUBNAME("TIMESTAMP");
  { FCNCALL_CALL_CTRL_WRAP(TIMESTAMP,TIMESTAMP.FCNCALL_CALL(TIMESTAMP)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_LOS LOS[1];
  {
  FCNCALL_SUBNAME("LOS");
  FCNCALL_FOR(__i0,1)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(LOS__i0,,__i0,LOS[__i0].FCNCALL_CALL(LOS[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_ROLU ROLU[1];
  {
  FCNCALL_SUBNAME("ROLU");
  FCNCALL_FOR(__i0,1)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(ROLU__i0,,__i0,ROLU[__i0].FCNCALL_CALL(ROLU[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_S S[8];
  {
  FCNCALL_SUBNAME("S");
  FCNCALL_FOR(__i0,8)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(S__i0,,__i0,S[__i0].FCNCALL_CALL(S[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<raw_event_SST,raw_event_SST,1024> SST[4];
  {
  FCNCALL_SUBNAME("SST");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(SST__i0,,__i0,SST[__i0].FCNCALL_CALL(SST[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_FIBTEN FIBTEN;
  {
  FCNCALL_SUBNAME("FIBTEN");
  { FCNCALL_CALL_CTRL_WRAP(FIBTEN,FIBTEN.FCNCALL_CALL(FIBTEN)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_FIBELEVEN FIBELEVEN;
  {
  FCNCALL_SUBNAME("FIBELEVEN");
  { FCNCALL_CALL_CTRL_WRAP(FIBELEVEN,FIBELEVEN.FCNCALL_CALL(FIBELEVEN)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_FIBTWELVE FIBTWELVE;
  {
  FCNCALL_SUBNAME("FIBTWELVE");
  { FCNCALL_CALL_CTRL_WRAP(FIBTWELVE,FIBTWELVE.FCNCALL_CALL(FIBTWELVE)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_FIBTHIRTEEN FIBTHIRTEEN;
  {
  FCNCALL_SUBNAME("FIBTHIRTEEN");
  { FCNCALL_CALL_CTRL_WRAP(FIBTHIRTEEN,FIBTHIRTEEN.FCNCALL_CALL(FIBTHIRTEEN)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_FIBTHREEA FIBTHREEA;
  {
  FCNCALL_SUBNAME("FIBTHREEA");
  { FCNCALL_CALL_CTRL_WRAP(FIBTHREEA,FIBTHREEA.FCNCALL_CALL(FIBTHREEA)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_FIBTHREEB FIBTHREEB;
  {
  FCNCALL_SUBNAME("FIBTHREEB");
  { FCNCALL_CALL_CTRL_WRAP(FIBTHREEB,FIBTHREEB.FCNCALL_CALL(FIBTHREEB)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TOFD TOFD;
  {
  FCNCALL_SUBNAME("TOFD");
  { FCNCALL_CALL_CTRL_WRAP(TOFD,TOFD.FCNCALL_CALL(TOFD)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_CALIFA CALIFA;
  {
  FCNCALL_SUBNAME("CALIFA");
  { FCNCALL_CALL_CTRL_WRAP(CALIFA,CALIFA.FCNCALL_CALL(CALIFA)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA32,DATA32,128,20> PSPX[6];
  {
  FCNCALL_SUBNAME("PSPX");
  FCNCALL_FOR(__i0,6)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(PSPX__i0,,__i0,PSPX[__i0].FCNCALL_CALL(PSPX[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_NN NN;
  {
  FCNCALL_SUBNAME("NN");
  { FCNCALL_CALL_CTRL_WRAP(NN,NN.FCNCALL_CALL(NN)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event

#include "gen/default_fcncall_undef.hh"


/** END_FUNCTION_CALL_PER_MEMBER **************************************/
