#########################################################
# Specify the name of the target executable

TARGETS:=s306

#########################################################
# Include common Makefile

include ../makefile_common.mk
