#########################################################
# Specify the name of the target executable

TARGETS:=rpc2009

#########################################################
# Include common Makefile

include ../makefile_common.mk
