#########################################################
# Specify the name of the target executable

TARGETS:=201810_s444

#########################################################
# Include common Makefile

include ../makefile_common.mk
