#include "mapping_timestamp.hh"
#include "mapping_los.hh"
#include "mapping_s8.hh"
#include "mapping_sst.hh"
#include "gen/mapping_fiber.hh"
#include "gen/mapping_tofd.hh"
#include "mapping_CALIFA.hh"
