/** BEGIN_FUNCTION_CALL_PER_MEMBER *************************************
 *
 * Recursive function calls per member.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_fcncall_define.hh"

#ifndef USER_DEF_raw_event_SCITWO
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SCITWO)::FCNCALL_NAME(raw_event_SCITWO)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,8,32> VTF;
  {
  FCNCALL_SUBNAME("VTF");
  { FCNCALL_CALL_CTRL_WRAP(VTF,VTF.FCNCALL_CALL(VTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16,DATA16,8,32> VTC;
  {
  FCNCALL_SUBNAME("VTC");
  { FCNCALL_CALL_CTRL_WRAP(VTC,VTC.FCNCALL_CALL(VTC)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SCITWO

#ifndef USER_DEF_raw_event_SCIEIGHT
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SCIEIGHT)::FCNCALL_NAME(raw_event_SCIEIGHT)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,8,32> VTF;
  {
  FCNCALL_SUBNAME("VTF");
  { FCNCALL_CALL_CTRL_WRAP(VTF,VTF.FCNCALL_CALL(VTF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16,DATA16,8,32> VTC;
  {
  FCNCALL_SUBNAME("VTC");
  { FCNCALL_CALL_CTRL_WRAP(VTC,VTC.FCNCALL_CALL(VTC)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SCIEIGHT

#ifndef USER_DEF_raw_event_NN_WR
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_WR)::FCNCALL_NAME(raw_event_NN_WR)
{
  FCNCALL_INIT;
  // DATA12 ID;
  {
  FCNCALL_SUBNAME("ID");
  { FCNCALL_CALL_CTRL_WRAP(ID,ID.FCNCALL_CALL(ID)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA16 T[4];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_WR

#ifndef USER_DEF_raw_event_NN_P_tcl_T
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tcl_T)::FCNCALL_NAME(raw_event_NN_P_tcl_T)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,50,200> B;
  {
  FCNCALL_SUBNAME("B");
  { FCNCALL_CALL_CTRL_WRAP(B,B.FCNCALL_CALL(B)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tcl_T

#ifndef USER_DEF_raw_event_NN_P_tcl
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tcl)::FCNCALL_NAME(raw_event_NN_P_tcl)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tcl_T T[2];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tcl

#ifndef USER_DEF_raw_event_NN_P_tfl_T
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tfl_T)::FCNCALL_NAME(raw_event_NN_P_tfl_T)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,50,200> B;
  {
  FCNCALL_SUBNAME("B");
  { FCNCALL_CALL_CTRL_WRAP(B,B.FCNCALL_CALL(B)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tfl_T

#ifndef USER_DEF_raw_event_NN_P_tfl
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tfl)::FCNCALL_NAME(raw_event_NN_P_tfl)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tfl_T T[2];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tfl

#ifndef USER_DEF_raw_event_NN_P_tct_T
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tct_T)::FCNCALL_NAME(raw_event_NN_P_tct_T)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,50,200> B;
  {
  FCNCALL_SUBNAME("B");
  { FCNCALL_CALL_CTRL_WRAP(B,B.FCNCALL_CALL(B)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tct_T

#ifndef USER_DEF_raw_event_NN_P_tct
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tct)::FCNCALL_NAME(raw_event_NN_P_tct)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tct_T T[2];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tct

#ifndef USER_DEF_raw_event_NN_P_tft_T
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tft_T)::FCNCALL_NAME(raw_event_NN_P_tft_T)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,50,200> B;
  {
  FCNCALL_SUBNAME("B");
  { FCNCALL_CALL_CTRL_WRAP(B,B.FCNCALL_CALL(B)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tft_T

#ifndef USER_DEF_raw_event_NN_P_tft
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P_tft)::FCNCALL_NAME(raw_event_NN_P_tft)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tft_T T[2];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P_tft

#ifndef USER_DEF_raw_event_NN_P
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN_P)::FCNCALL_NAME(raw_event_NN_P)
{
  FCNCALL_INIT;
  // raw_event_NN_P_tcl tcl;
  {
  FCNCALL_SUBNAME("tcl");
  { FCNCALL_CALL_CTRL_WRAP(tcl,tcl.FCNCALL_CALL(tcl)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_NN_P_tfl tfl;
  {
  FCNCALL_SUBNAME("tfl");
  { FCNCALL_CALL_CTRL_WRAP(tfl,tfl.FCNCALL_CALL(tfl)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_NN_P_tct tct;
  {
  FCNCALL_SUBNAME("tct");
  { FCNCALL_CALL_CTRL_WRAP(tct,tct.FCNCALL_CALL(tct)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_NN_P_tft tft;
  {
  FCNCALL_SUBNAME("tft");
  { FCNCALL_CALL_CTRL_WRAP(tft,tft.FCNCALL_CALL(tft)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN_P

#ifndef USER_DEF_raw_event_NN
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_NN)::FCNCALL_NAME(raw_event_NN)
{
  FCNCALL_INIT;
  // raw_event_NN_WR WR;
  {
  FCNCALL_SUBNAME("WR");
  { FCNCALL_CALL_CTRL_WRAP(WR,WR.FCNCALL_CALL(WR)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_NN_P P[16];
  {
  FCNCALL_SUBNAME("P");
  FCNCALL_FOR(__i0,16)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(P__i0,,__i0,P[__i0].FCNCALL_CALL(P[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_NN

#ifndef USER_DEF_raw_event_MUSIC
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_MUSIC)::FCNCALL_NAME(raw_event_MUSIC)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA16_OVERFLOW,DATA16_OVERFLOW,8,100> E;
  {
  FCNCALL_SUBNAME("E");
  { FCNCALL_CALL_CTRL_WRAP(E,E.FCNCALL_CALL(E)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16_OVERFLOW,DATA16_OVERFLOW,8,100> T;
  {
  FCNCALL_SUBNAME("T");
  { FCNCALL_CALL_CTRL_WRAP(T,T.FCNCALL_CALL(T)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16_OVERFLOW,DATA16_OVERFLOW,2,100> TREF;
  {
  FCNCALL_SUBNAME("TREF");
  { FCNCALL_CALL_CTRL_WRAP(TREF,TREF.FCNCALL_CALL(TREF)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_MUSIC

#ifndef USER_DEF_raw_event_SOFSCI
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SOFSCI)::FCNCALL_NAME(raw_event_SOFSCI)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,3,10> TF;
  {
  FCNCALL_SUBNAME("TF");
  { FCNCALL_CALL_CTRL_WRAP(TF,TF.FCNCALL_CALL(TF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16,DATA16,3,10> TC;
  {
  FCNCALL_SUBNAME("TC");
  { FCNCALL_CALL_CTRL_WRAP(TC,TC.FCNCALL_CALL(TC)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SOFSCI

#ifndef USER_DEF_raw_event_SOFTWIM_S
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SOFTWIM_S)::FCNCALL_NAME(raw_event_SOFTWIM_S)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA16_OVERFLOW,DATA16_OVERFLOW,16,100> E;
  {
  FCNCALL_SUBNAME("E");
  { FCNCALL_CALL_CTRL_WRAP(E,E.FCNCALL_CALL(E)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16_OVERFLOW,DATA16_OVERFLOW,16,100> T;
  {
  FCNCALL_SUBNAME("T");
  { FCNCALL_CALL_CTRL_WRAP(T,T.FCNCALL_CALL(T)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16_OVERFLOW,DATA16_OVERFLOW,2,100> TREF;
  {
  FCNCALL_SUBNAME("TREF");
  { FCNCALL_CALL_CTRL_WRAP(TREF,TREF.FCNCALL_CALL(TREF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16_OVERFLOW,DATA16_OVERFLOW,2,100> TRIG;
  {
  FCNCALL_SUBNAME("TRIG");
  { FCNCALL_CALL_CTRL_WRAP(TRIG,TRIG.FCNCALL_CALL(TRIG)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SOFTWIM_S

#ifndef USER_DEF_raw_event_SOFTWIM
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SOFTWIM)::FCNCALL_NAME(raw_event_SOFTWIM)
{
  FCNCALL_INIT;
  // raw_event_SOFTWIM_S S[1];
  {
  FCNCALL_SUBNAME("S");
  FCNCALL_FOR(__i0,1)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(S__i0,,__i0,S[__i0].FCNCALL_CALL(S[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SOFTWIM

#ifndef USER_DEF_raw_event_SOFTOFW_P
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SOFTOFW_P)::FCNCALL_NAME(raw_event_SOFTOFW_P)
{
  FCNCALL_INIT;
  // raw_array_multi_zero_suppress<DATA12,DATA12,2,10> TF;
  {
  FCNCALL_SUBNAME("TF");
  { FCNCALL_CALL_CTRL_WRAP(TF,TF.FCNCALL_CALL(TF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_multi_zero_suppress<DATA16,DATA16,2,10> TC;
  {
  FCNCALL_SUBNAME("TC");
  { FCNCALL_CALL_CTRL_WRAP(TC,TC.FCNCALL_CALL(TC)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA14 E[2];
  {
  FCNCALL_SUBNAME("E");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(E__i0,,__i0,E[__i0].FCNCALL_CALL(E[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SOFTOFW_P

#ifndef USER_DEF_raw_event_SOFTOFW
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SOFTOFW)::FCNCALL_NAME(raw_event_SOFTOFW)
{
  FCNCALL_INIT;
  // raw_event_SOFTOFW_P P[28];
  {
  FCNCALL_SUBNAME("P");
  FCNCALL_FOR(__i0,28)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(P__i0,,__i0,P[__i0].FCNCALL_CALL(P[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SOFTOFW

#ifndef USER_DEF_raw_event_SOFMWPC_Plane
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SOFMWPC_Plane)::FCNCALL_NAME(raw_event_SOFMWPC_Plane)
{
  FCNCALL_INIT;
  // raw_array_zero_suppress<DATA12,DATA12,288> Q;
  {
  FCNCALL_SUBNAME("Q");
  { FCNCALL_CALL_CTRL_WRAP(Q,Q.FCNCALL_CALL(Q)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SOFMWPC_Plane

#ifndef USER_DEF_raw_event_SOFMWPC
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SOFMWPC)::FCNCALL_NAME(raw_event_SOFMWPC)
{
  FCNCALL_INIT;
  // raw_event_SOFMWPC_Plane Plane[3];
  {
  FCNCALL_SUBNAME("Plane");
  FCNCALL_FOR(__i0,3)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(Plane__i0,,__i0,Plane[__i0].FCNCALL_CALL(Plane[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SOFMWPC

#ifndef USER_DEF_raw_event_SOFSCALERS
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SOFSCALERS)::FCNCALL_NAME(raw_event_SOFSCALERS)
{
  FCNCALL_INIT;
  // DATA32 UPSTREAM[7];
  {
  FCNCALL_SUBNAME("UPSTREAM");
  FCNCALL_FOR(__i0,7)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(UPSTREAM__i0,,__i0,UPSTREAM[__i0].FCNCALL_CALL(UPSTREAM[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 TOFW[56];
  {
  FCNCALL_SUBNAME("TOFW");
  FCNCALL_FOR(__i0,56)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(TOFW__i0,,__i0,TOFW[__i0].FCNCALL_CALL(TOFW[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SOFSCALERS

#ifndef USER_DEF_raw_event_CALIFA
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_CALIFA)::FCNCALL_NAME(raw_event_CALIFA)
{
  FCNCALL_INIT;
  // raw_array_zero_suppress<DATA16,DATA16,4861> ENE;
  {
  FCNCALL_SUBNAME("ENE");
  { FCNCALL_CALL_CTRL_WRAP(ENE,ENE.FCNCALL_CALL(ENE)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA16,DATA16,4861> TOT;
  {
  FCNCALL_SUBNAME("TOT");
  { FCNCALL_CALL_CTRL_WRAP(TOT,TOT.FCNCALL_CALL(TOT)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA32,DATA32,4861> TSLSB;
  {
  FCNCALL_SUBNAME("TSLSB");
  { FCNCALL_CALL_CTRL_WRAP(TSLSB,TSLSB.FCNCALL_CALL(TSLSB)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA32,DATA32,4861> TSMSB;
  {
  FCNCALL_SUBNAME("TSMSB");
  { FCNCALL_CALL_CTRL_WRAP(TSMSB,TSMSB.FCNCALL_CALL(TSMSB)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA16,DATA16,4861> NF;
  {
  FCNCALL_SUBNAME("NF");
  { FCNCALL_CALL_CTRL_WRAP(NF,NF.FCNCALL_CALL(NF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA16,DATA16,4861> NS;
  {
  FCNCALL_SUBNAME("NS");
  { FCNCALL_CALL_CTRL_WRAP(NS,NS.FCNCALL_CALL(NS)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_CALIFA

#ifndef USER_DEF_raw_event_TIMESTAMP_SCITWO_WR
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_SCITWO_WR)::FCNCALL_NAME(raw_event_TIMESTAMP_SCITWO_WR)
{
  FCNCALL_INIT;
  // DATA16 T[4];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_SCITWO_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_SCITWO
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_SCITWO)::FCNCALL_NAME(raw_event_TIMESTAMP_SCITWO)
{
  FCNCALL_INIT;
  // DATA12 ID;
  {
  FCNCALL_SUBNAME("ID");
  { FCNCALL_CALL_CTRL_WRAP(ID,ID.FCNCALL_CALL(ID)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_SCITWO_WR WR;
  {
  FCNCALL_SUBNAME("WR");
  { FCNCALL_CALL_CTRL_WRAP(WR,WR.FCNCALL_CALL(WR)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_SCITWO

#ifndef USER_DEF_raw_event_TIMESTAMP_SCIEIGHT_WR
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_SCIEIGHT_WR)::FCNCALL_NAME(raw_event_TIMESTAMP_SCIEIGHT_WR)
{
  FCNCALL_INIT;
  // DATA16 T[4];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_SCIEIGHT_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_SCIEIGHT
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_SCIEIGHT)::FCNCALL_NAME(raw_event_TIMESTAMP_SCIEIGHT)
{
  FCNCALL_INIT;
  // DATA12 ID;
  {
  FCNCALL_SUBNAME("ID");
  { FCNCALL_CALL_CTRL_WRAP(ID,ID.FCNCALL_CALL(ID)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_SCIEIGHT_WR WR;
  {
  FCNCALL_SUBNAME("WR");
  { FCNCALL_CALL_CTRL_WRAP(WR,WR.FCNCALL_CALL(WR)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_SCIEIGHT

#ifndef USER_DEF_raw_event_TIMESTAMP_CALIFA_WR
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_CALIFA_WR)::FCNCALL_NAME(raw_event_TIMESTAMP_CALIFA_WR)
{
  FCNCALL_INIT;
  // DATA16 T[4];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_CALIFA_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_CALIFA
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_CALIFA)::FCNCALL_NAME(raw_event_TIMESTAMP_CALIFA)
{
  FCNCALL_INIT;
  // DATA12 ID;
  {
  FCNCALL_SUBNAME("ID");
  { FCNCALL_CALL_CTRL_WRAP(ID,ID.FCNCALL_CALL(ID)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_CALIFA_WR WR;
  {
  FCNCALL_SUBNAME("WR");
  { FCNCALL_CALL_CTRL_WRAP(WR,WR.FCNCALL_CALL(WR)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_CALIFA

#ifndef USER_DEF_raw_event_TIMESTAMP_MASTER_WR
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_MASTER_WR)::FCNCALL_NAME(raw_event_TIMESTAMP_MASTER_WR)
{
  FCNCALL_INIT;
  // DATA16 T[4];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_MASTER_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_MASTER
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_MASTER)::FCNCALL_NAME(raw_event_TIMESTAMP_MASTER)
{
  FCNCALL_INIT;
  // DATA12 ID;
  {
  FCNCALL_SUBNAME("ID");
  { FCNCALL_CALL_CTRL_WRAP(ID,ID.FCNCALL_CALL(ID)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_MASTER_WR WR;
  {
  FCNCALL_SUBNAME("WR");
  { FCNCALL_CALL_CTRL_WRAP(WR,WR.FCNCALL_CALL(WR)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_MASTER

#ifndef USER_DEF_raw_event_TIMESTAMP_SOFIA_WR
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_SOFIA_WR)::FCNCALL_NAME(raw_event_TIMESTAMP_SOFIA_WR)
{
  FCNCALL_INIT;
  // DATA16 T[4];
  {
  FCNCALL_SUBNAME("T");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(T__i0,,__i0,T[__i0].FCNCALL_CALL(T[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_SOFIA_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_SOFIA
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP_SOFIA)::FCNCALL_NAME(raw_event_TIMESTAMP_SOFIA)
{
  FCNCALL_INIT;
  // DATA12 ID;
  {
  FCNCALL_SUBNAME("ID");
  { FCNCALL_CALL_CTRL_WRAP(ID,ID.FCNCALL_CALL(ID)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_SOFIA_WR WR;
  {
  FCNCALL_SUBNAME("WR");
  { FCNCALL_CALL_CTRL_WRAP(WR,WR.FCNCALL_CALL(WR)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP_SOFIA

#ifndef USER_DEF_raw_event_TIMESTAMP
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TIMESTAMP)::FCNCALL_NAME(raw_event_TIMESTAMP)
{
  FCNCALL_INIT;
  // raw_event_TIMESTAMP_SCITWO SCITWO;
  {
  FCNCALL_SUBNAME("SCITWO");
  { FCNCALL_CALL_CTRL_WRAP(SCITWO,SCITWO.FCNCALL_CALL(SCITWO)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_SCIEIGHT SCIEIGHT;
  {
  FCNCALL_SUBNAME("SCIEIGHT");
  { FCNCALL_CALL_CTRL_WRAP(SCIEIGHT,SCIEIGHT.FCNCALL_CALL(SCIEIGHT)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_CALIFA CALIFA[2];
  {
  FCNCALL_SUBNAME("CALIFA");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(CALIFA__i0,,__i0,CALIFA[__i0].FCNCALL_CALL(CALIFA[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_MASTER MASTER;
  {
  FCNCALL_SUBNAME("MASTER");
  { FCNCALL_CALL_CTRL_WRAP(MASTER,MASTER.FCNCALL_CALL(MASTER)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP_SOFIA SOFIA;
  {
  FCNCALL_SUBNAME("SOFIA");
  { FCNCALL_CALL_CTRL_WRAP(SOFIA,SOFIA.FCNCALL_CALL(SOFIA)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TIMESTAMP

#ifndef USER_DEF_raw_event
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event)::FCNCALL_NAME(raw_event)
{
  FCNCALL_INIT;
  FCNCALL_CALL_CTRL_WRAP(raw_event_base,FCNCALL_CLASS_NAME(raw_event_base)::FCNCALL_CALL_BASE());
  // raw_event_SCITWO SCITWO;
  {
  FCNCALL_SUBNAME("SCITWO");
  { FCNCALL_CALL_CTRL_WRAP(SCITWO,SCITWO.FCNCALL_CALL(SCITWO)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_SCIEIGHT SCIEIGHT;
  {
  FCNCALL_SUBNAME("SCIEIGHT");
  { FCNCALL_CALL_CTRL_WRAP(SCIEIGHT,SCIEIGHT.FCNCALL_CALL(SCIEIGHT)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_NN NN;
  {
  FCNCALL_SUBNAME("NN");
  { FCNCALL_CALL_CTRL_WRAP(NN,NN.FCNCALL_CALL(NN)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_array_zero_suppress<DATA32,DATA32,512> SAMP;
  {
  FCNCALL_SUBNAME("SAMP");
  { FCNCALL_CALL_CTRL_WRAP(SAMP,SAMP.FCNCALL_CALL(SAMP)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_MUSIC MUSIC;
  {
  FCNCALL_SUBNAME("MUSIC");
  { FCNCALL_CALL_CTRL_WRAP(MUSIC,MUSIC.FCNCALL_CALL(MUSIC)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_SOFSCI SOFSCI[1];
  {
  FCNCALL_SUBNAME("SOFSCI");
  FCNCALL_FOR(__i0,1)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(SOFSCI__i0,,__i0,SOFSCI[__i0].FCNCALL_CALL(SOFSCI[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_SOFTWIM SOFTWIM;
  {
  FCNCALL_SUBNAME("SOFTWIM");
  { FCNCALL_CALL_CTRL_WRAP(SOFTWIM,SOFTWIM.FCNCALL_CALL(SOFTWIM)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_SOFTOFW SOFTOFW;
  {
  FCNCALL_SUBNAME("SOFTOFW");
  { FCNCALL_CALL_CTRL_WRAP(SOFTOFW,SOFTOFW.FCNCALL_CALL(SOFTOFW)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_SOFMWPC SOFMWPC[4];
  {
  FCNCALL_SUBNAME("SOFMWPC");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(SOFMWPC__i0,,__i0,SOFMWPC[__i0].FCNCALL_CALL(SOFMWPC[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_SOFSCALERS SOFSCALERS;
  {
  FCNCALL_SUBNAME("SOFSCALERS");
  { FCNCALL_CALL_CTRL_WRAP(SOFSCALERS,SOFSCALERS.FCNCALL_CALL(SOFSCALERS)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_CALIFA CALIFA;
  {
  FCNCALL_SUBNAME("CALIFA");
  { FCNCALL_CALL_CTRL_WRAP(CALIFA,CALIFA.FCNCALL_CALL(CALIFA)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TIMESTAMP TIMESTAMP;
  {
  FCNCALL_SUBNAME("TIMESTAMP");
  { FCNCALL_CALL_CTRL_WRAP(TIMESTAMP,TIMESTAMP.FCNCALL_CALL(TIMESTAMP)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_list_ii_zero_suppress<DATA16,DATA16,170> TPAT;
  {
  FCNCALL_SUBNAME("TPAT");
  { FCNCALL_CALL_CTRL_WRAP(TPAT,TPAT.FCNCALL_CALL(TPAT)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event

#ifndef USER_DEF_raw_sticky
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_sticky)::FCNCALL_NAME(raw_sticky)
{
  FCNCALL_INIT;
  FCNCALL_CALL_CTRL_WRAP(raw_sticky_base,FCNCALL_CLASS_NAME(raw_sticky_base)::FCNCALL_CALL_BASE());
  FCNCALL_RET;
}
#endif//USER_DEF_raw_sticky

#include "gen/default_fcncall_undef.hh"


/** END_FUNCTION_CALL_PER_MEMBER **************************************/
