#########################################################
# Specify the name of the target executable

TARGETS:=s438b

#########################################################
# Include common Makefile

include ../makefile_common.mk
