#########################################################
# Specify the name of the target executable

TARGETS:=s438

#########################################################
# Include common Makefile

include ../makefile_common.mk
