/*********************************************************************
 *
 * This file is autogenerated by /u/taniuchi/s467/upexps/../ucesb/lu_common/make_acc_auto_def.sh
 *
 * Editing is useless.
 *
 *********************************************************************
 *
 * Input file:    /u/taniuchi/s467/upexps/../ucesb/acc_def/has_pthread_getname_np.h
 * Basename:      HAS_PTHREAD_GETNAME_NP
 * Compiler:      g++
 * Compiler args: -I. -DUNPACKERNAME=fzd_jan_2010 -DUNPACKER_IS_fzd_jan_2010 -I/u/taniuchi/s467/upexps/../ucesb/file_input -I/u/taniuchi/s467/upexps/../ucesb/file_input/lmd_struct -I/u/taniuchi/s467/upexps/../ucesb/threading -I/u/taniuchi/s467/upexps/../ucesb/lu_common -I/u/taniuchi/s467/upexps/../ucesb/acc_def -ansi -Wall -W -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wwrite-strings -Wconversion -g -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_LIMIT_MACROS -DHAVE_TEE -Igen_fzd_jan_2010 -DGENDIR="gen_fzd_jan_2010" -DUSE_EXT_WRITER= -DUSING_EXT_WRITER= -DEXT_WRITER_PREFIX="/u/taniuchi/s467/upexps/../ucesb/hbook/" -I/u/taniuchi/s467/upexps/../ucesb/hbook -DUSE_CURSES=1 -I/u/taniuchi/s467/upexps/../ucesb/watcher -DHAVE_THREAD_LOCAL_STORAGE -pthread -DUSE_PTHREAD=1 -DHAVE_PTHREAD -DUSE_LMD_INPUT=1 -DUSE_LMD_OUTPUT_TCP -I/u/taniuchi/s467/upexps/../ucesb/mapcalib
 *
 ********************************************************************/

#ifndef __AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__
#define __AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__

/*
 * Option: pthread_h
 * Option: notavail
 */
/*
 * -DACC_DEF_HAS_PTHREAD_GETNAME_NP_pthread_h



 * --> exit 0 (len 0)
 */
/*
 * -DACC_DEF_HAS_PTHREAD_GETNAME_NP_notavail



 * --> exit 0 (len 0)
 */

/********************************************************************/

#define ACC_DEF_HAS_PTHREAD_GETNAME_NP_pthread_h 1

/********************************************************************/

#endif/*__AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__*/
