#########################################################
# Specify the name of the target executable

TARGETS:=201905_tests

#########################################################
# Include common Makefile

include ../makefile_common.mk
