#########################################################
# Specify the name of the target executable

TARGETS:=xb2017

#########################################################
# Include common Makefile

include ../makefile_common.mk
