#########################################################
# Specify the name of the target executable

TARGETS:=201902_s473

#########################################################
# Include common Makefile

include ../makefile_common.mk
