#########################################################
# Specify the name of the target executable

TARGETS:=fzd_jan_2010

#########################################################
# Include common Makefile

include ../makefile_common.mk
