#########################################################
# Specify the name of the target executable

TARGETS:=s408

#########################################################
# Include common Makefile

include ../makefile_common.mk
