#########################################################
# Specify the name of the target executable

TARGETS:=dummy

#########################################################
# Include common Makefile

include ../makefile_common.mk
