// 1st choice mapping
//#define NUM_SFP_MODULES 2
//#define NUM_FEBEX_MODULES 25
//#define CHANNELS_PER_FEBEX 16

//SIGNAL(ZERO_SUPPRESS:CALIFA_CH_1);
SIGNAL(ZERO_SUPPRESS:CALIFA_ENE_1);
SIGNAL(ZERO_SUPPRESS:CALIFA_TSLSB_1);
SIGNAL(ZERO_SUPPRESS:CALIFA_TSMSB_1);
SIGNAL(ZERO_SUPPRESS:CALIFA_NF_1);
SIGNAL(ZERO_SUPPRESS:CALIFA_NS_1);

// CHANNEL VALUE
//SIGNAL(CALIFA_CH_1,califa.febex3.channel[0],CALIFA_CH_384,califa.febex3.channel[383],DATA8);

// ENERGY SIGNAL
SIGNAL(CALIFA_ENE_1,califa.febex3.energy[0],CALIFA_ENE_512,califa.febex3.energy[511],DATA16);

// TIME STAMP - least significant bit
SIGNAL(CALIFA_TSLSB_1,califa.febex3.ts_lsb[0],CALIFA_TSLSB_512,califa.febex3.ts_lsb[511],DATA32);

// TIME STAMP MOST SIGNIFICANT BITS
SIGNAL(CALIFA_TSMSB_1,califa.febex3.ts_msb[0],CALIFA_TSMSB_512,califa.febex3.ts_msb[511],DATA32);

// FAST ENERGY INTEGRAL
SIGNAL(CALIFA_NF_1,califa.febex3.n_f[0],CALIFA_NF_512,califa.febex3.n_f[511],DATA16);

// SLOW ENERGY INTEGRAL
SIGNAL(CALIFA_NS_1,califa.febex3.n_s[0],CALIFA_NS_512,califa.febex3.n_s[511],DATA16);
