#########################################################
# Specify the name of the target executable

TARGETS:=sis3316_async

#########################################################
# Include common Makefile

include ../makefile_common.mk
