#########################################################
# Specify the name of the target executable

TARGETS:=s327

#########################################################
# Include common Makefile

include ../makefile_common.mk
