#########################################################
# Specify the name of the target executable

TARGETS:=202002_s467

#########################################################
# Include common Makefile

include ../makefile_common.mk
