/** BEGIN_MIRROR_STRUCT ************************************************
 *
 * Mirror (1 to 1) structure.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_mirror_define.hh"

#ifndef USER_DEF_raw_event_LOS
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_LOS)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),4,32> STRUCT_MIRROR_NAME(TF);
  STRUCT_MIRROR_ITEM_CTRL(TC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),4,32> STRUCT_MIRROR_NAME(TC);
  STRUCT_MIRROR_FCNS_DECL(raw_event_LOS);
};
#endif//USER_DEF_raw_event_LOS

#ifndef USER_DEF_raw_event_TOFD_VFTX
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TOFD_VFTX)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,3);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[3]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TOFD_VFTX);
};
#endif//USER_DEF_raw_event_TOFD_VFTX

#ifndef USER_DEF_raw_event_TOFD_P_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TOFD_P_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TFL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),6,32> STRUCT_MIRROR_NAME(TFL);
  STRUCT_MIRROR_ITEM_CTRL(TFT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),6,32> STRUCT_MIRROR_NAME(TFT);
  STRUCT_MIRROR_ITEM_CTRL(TCL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),6,32> STRUCT_MIRROR_NAME(TCL);
  STRUCT_MIRROR_ITEM_CTRL(TCT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),6,32> STRUCT_MIRROR_NAME(TCT);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TOFD_P_T);
};
#endif//USER_DEF_raw_event_TOFD_P_T

#ifndef USER_DEF_raw_event_TOFD_P
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TOFD_P)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_TOFD_P_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TOFD_P);
};
#endif//USER_DEF_raw_event_TOFD_P

#ifndef USER_DEF_raw_event_TOFD
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TOFD)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(VFTX);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(VFTX__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_TOFD_VFTX) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(VFTX[2]);
  STRUCT_MIRROR_ITEM_CTRL(P);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(P__i0,,6);
  STRUCT_MIRROR_TYPE(raw_event_TOFD_P) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(P[6]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TOFD);
};
#endif//USER_DEF_raw_event_TOFD

#ifndef USER_DEF_raw_event_PSPXT
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_PSPXT)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(Tr);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),400> STRUCT_MIRROR_NAME(Tr);
  STRUCT_MIRROR_FCNS_DECL(raw_event_PSPXT);
};
#endif//USER_DEF_raw_event_PSPXT

#ifndef USER_DEF_raw_event_TIMESTAMP_MASTER_WR
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_MASTER_WR)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,4);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[4]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_MASTER_WR);
};
#endif//USER_DEF_raw_event_TIMESTAMP_MASTER_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_MASTER
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_MASTER)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(ID);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ID);
  STRUCT_MIRROR_ITEM_CTRL(WR);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_MASTER_WR) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(WR);
  STRUCT_MIRROR_ITEM_CTRL(HI);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(HI);
  STRUCT_MIRROR_ITEM_CTRL(LO);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LO);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_MASTER);
};
#endif//USER_DEF_raw_event_TIMESTAMP_MASTER

#ifndef USER_DEF_raw_event_TIMESTAMP
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(MASTER);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_MASTER) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(MASTER);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP);
};
#endif//USER_DEF_raw_event_TIMESTAMP

#ifndef USER_DEF_raw_event_TRLO_SAMPLER
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TRLO_SAMPLER)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(S);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),512> STRUCT_MIRROR_NAME(S);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TRLO_SAMPLER);
};
#endif//USER_DEF_raw_event_TRLO_SAMPLER

#ifndef USER_DEF_raw_event_TRLO
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TRLO)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(SAMPLER);
  STRUCT_MIRROR_TYPE(raw_event_TRLO_SAMPLER) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SAMPLER);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TRLO);
};
#endif//USER_DEF_raw_event_TRLO

#ifndef USER_DEF_raw_event_FIFILTER
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FIFILTER)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),200> STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FIFILTER);
};
#endif//USER_DEF_raw_event_FIFILTER

#ifndef USER_DEF_raw_event_FITRACE
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FITRACE)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),200> STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FITRACE);
};
#endif//USER_DEF_raw_event_FITRACE

#ifndef USER_DEF_raw_event_FITEST
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FITEST)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),64,64> STRUCT_MIRROR_NAME(TF);
  STRUCT_MIRROR_ITEM_CTRL(TC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),64,64> STRUCT_MIRROR_NAME(TC);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FITEST);
};
#endif//USER_DEF_raw_event_FITEST

#ifndef USER_DEF_raw_event_FITRACK
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FITRACK)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(t);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),16,32> STRUCT_MIRROR_NAME(t);
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),16,32> STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FITRACK);
};
#endif//USER_DEF_raw_event_FITRACK

#ifndef USER_DEF_raw_event_SIPD
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SIPD)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA14_OVERFLOW),STRUCT_MIRROR_TEMPLATE_ARG(DATA14_OVERFLOW),8> STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SIPD);
};
#endif//USER_DEF_raw_event_SIPD

#ifndef USER_DEF_raw_event_STRAW_S
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_STRAW_S)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),32,200> STRUCT_MIRROR_NAME(TF);
  STRUCT_MIRROR_ITEM_CTRL(TC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),32,200> STRUCT_MIRROR_NAME(TC);
  STRUCT_MIRROR_ITEM_CTRL(TRIG);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TRIG);
  STRUCT_MIRROR_FCNS_DECL(raw_event_STRAW_S);
};
#endif//USER_DEF_raw_event_STRAW_S

#ifndef USER_DEF_raw_event_STRAW
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_STRAW)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(S);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(S__i0,,1);
  STRUCT_MIRROR_TYPE(raw_event_STRAW_S) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(S[1]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_STRAW);
};
#endif//USER_DEF_raw_event_STRAW

#ifndef USER_DEF_raw_event
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event) : public STRUCT_MIRROR_BASE(raw_event_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_event_base);
  STRUCT_MIRROR_ITEM_CTRL(LOS);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(LOS__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_LOS) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LOS[2]);
  STRUCT_MIRROR_ITEM_CTRL(TOFD);
  STRUCT_MIRROR_TYPE(raw_event_TOFD) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TOFD);
  STRUCT_MIRROR_ITEM_CTRL(PSPX);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(PSPX__i0,,5);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),65,20> STRUCT_MIRROR_NAME(PSPX[5]);
  STRUCT_MIRROR_ITEM_CTRL(PSPXT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(PSPXT__i0,,5);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(PSPXT__i0__i1,[5],65);
  STRUCT_MIRROR_TYPE(raw_event_PSPXT) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(PSPXT[5][65]);
  STRUCT_MIRROR_ITEM_CTRL(TIMESTAMP);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TIMESTAMP);
  STRUCT_MIRROR_ITEM_CTRL(TRLO);
  STRUCT_MIRROR_TYPE(raw_event_TRLO) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TRLO);
  STRUCT_MIRROR_ITEM_CTRL(FIFILTER);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(FIFILTER__i0,,10);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(FIFILTER__i0__i1,[10],16);
  STRUCT_MIRROR_TYPE(raw_event_FIFILTER) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FIFILTER[10][16]);
  STRUCT_MIRROR_ITEM_CTRL(FITRACE);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(FITRACE__i0,,10);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(FITRACE__i0__i1,[10],16);
  STRUCT_MIRROR_TYPE(raw_event_FITRACE) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FITRACE[10][16]);
  STRUCT_MIRROR_ITEM_CTRL(FITEST);
  STRUCT_MIRROR_TYPE(raw_event_FITEST) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FITEST);
  STRUCT_MIRROR_ITEM_CTRL(FITRACK);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(FITRACK__i0,,10);
  STRUCT_MIRROR_TYPE(raw_event_FITRACK) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FITRACK[10]);
  STRUCT_MIRROR_ITEM_CTRL(SIPD);
  STRUCT_MIRROR_TYPE(raw_event_SIPD) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SIPD);
  STRUCT_MIRROR_ITEM_CTRL(STRAW);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(STRAW__i0,,1);
  STRUCT_MIRROR_TYPE(raw_event_STRAW) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(STRAW[1]);
  STRUCT_MIRROR_FCNS_DECL(raw_event);
};
#endif//USER_DEF_raw_event

#ifndef USER_DEF_raw_sticky
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_sticky) : public STRUCT_MIRROR_BASE(raw_sticky_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_sticky_base);
  STRUCT_MIRROR_FCNS_DECL(raw_sticky);
};
#endif//USER_DEF_raw_sticky

#include "gen/default_mirror_undef.hh"


/** END_MIRROR_STRUCT *************************************************/
