/*********************************************************************
 *
 * This file is autogenerated by /u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/lu_common/make_acc_auto_def.sh
 *
 * Editing is useless.
 *
 *********************************************************************
 *
 * Input file:    /u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h
 * Basename:      BYTESWAP_INCLUDE
 * Compiler:      g++
 * Compiler args: -I. -DUNPACKERNAME=201902_s473 -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/file_input -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/file_input/lmd_struct -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/threading -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/lu_common -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def -ansi -Wall -W -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wwrite-strings -Wconversion -g -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_LIMIT_MACROS -DHAVE_TEE -Igen_201902_s473 -DGENDIR="gen_201902_s473" -DUSE_EXT_WRITER= -DUSING_EXT_WRITER= -DEXT_WRITER_PREFIX="/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/hbook/" -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/hbook -DUSE_CURSES=1 -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/watcher -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/u/land/fake_cvmfs/upexps/201902_s473/../landdaq_/vidsel/siderem -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/dets/sst -std=c++11 -DCONTROL_INCLUDE -I./../land_common -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/dets/sst -DHAVE_THREAD_LOCAL_STORAGE -pthread -DUSE_PTHREAD=1 -DHAVE_PTHREAD -DUSE_LMD_INPUT=1 -DUSE_LMD_OUTPUT_TCP -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/mapcalib
 *
 ********************************************************************/

#ifndef __AUTO_DEF__BYTESWAP_INCLUDE_HH__
#define __AUTO_DEF__BYTESWAP_INCLUDE_HH__

/*
 * Option: byteswap_h
 * Option: endian_h
 * Option: sys_endian_h
 * Option: machine_endian_h
 * Option: machine_endian_h
 * Option: machine_endian_h
 * Option: machine_bswap_h
 * Option: sys_types_h
 * Option: mybyteswap
 */
/*
 * -DACC_DEF_BYTESWAP_INCLUDE_byteswap_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C

 * --> exit 0 (len 88)
 */
/*
 * -DACC_DEF_BYTESWAP_INCLUDE_endian_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:89:3: error: #error bswap_16 not defined
 # error bswap_16 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:92:3: error: #error bswap_32 not defined
 # error bswap_32 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h: In function ‘acc_test_func’:
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:96:10: warning: implicit declaration of function ‘bswap_16’ [-Wimplicit-function-declaration]
   (void) bswap_16(1);
          ^~~~~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:97:10: warning: implicit declaration of function ‘bswap_32’ [-Wimplicit-function-declaration]
   (void) bswap_32(1);
          ^~~~~~~~

 * --> exit 1 (len 942)
 */
/*
 * -DACC_DEF_BYTESWAP_INCLUDE_sys_endian_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:89:3: error: #error bswap_16 not defined
 # error bswap_16 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:92:3: error: #error bswap_32 not defined
 # error bswap_32 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h: In function ‘acc_test_func’:
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:96:10: warning: implicit declaration of function ‘bswap_16’ [-Wimplicit-function-declaration]
   (void) bswap_16(1);
          ^~~~~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:97:10: warning: implicit declaration of function ‘bswap_32’ [-Wimplicit-function-declaration]
   (void) bswap_32(1);
          ^~~~~~~~

 * --> exit 1 (len 942)
 */
/*
 * -DACC_DEF_BYTESWAP_INCLUDE_machine_endian_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:89:3: error: #error bswap_16 not defined
 # error bswap_16 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:92:3: error: #error bswap_32 not defined
 # error bswap_32 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h: In function ‘acc_test_func’:
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:96:10: warning: implicit declaration of function ‘bswap_16’ [-Wimplicit-function-declaration]
   (void) bswap_16(1);
          ^~~~~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:97:10: warning: implicit declaration of function ‘bswap_32’ [-Wimplicit-function-declaration]
   (void) bswap_32(1);
          ^~~~~~~~

 * --> exit 1 (len 942)
 */
/*
 * -DACC_DEF_BYTESWAP_INCLUDE_machine_endian_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:89:3: error: #error bswap_16 not defined
 # error bswap_16 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:92:3: error: #error bswap_32 not defined
 # error bswap_32 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h: In function ‘acc_test_func’:
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:96:10: warning: implicit declaration of function ‘bswap_16’ [-Wimplicit-function-declaration]
   (void) bswap_16(1);
          ^~~~~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:97:10: warning: implicit declaration of function ‘bswap_32’ [-Wimplicit-function-declaration]
   (void) bswap_32(1);
          ^~~~~~~~

 * --> exit 1 (len 942)
 */
/*
 * -DACC_DEF_BYTESWAP_INCLUDE_machine_endian_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:89:3: error: #error bswap_16 not defined
 # error bswap_16 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:92:3: error: #error bswap_32 not defined
 # error bswap_32 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h: In function ‘acc_test_func’:
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:96:10: warning: implicit declaration of function ‘bswap_16’ [-Wimplicit-function-declaration]
   (void) bswap_16(1);
          ^~~~~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:97:10: warning: implicit declaration of function ‘bswap_32’ [-Wimplicit-function-declaration]
   (void) bswap_32(1);
          ^~~~~~~~

 * --> exit 1 (len 942)
 */
/*
 * -DACC_DEF_BYTESWAP_INCLUDE_machine_bswap_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:89:3: error: #error bswap_16 not defined
 # error bswap_16 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:92:3: error: #error bswap_32 not defined
 # error bswap_32 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h: In function ‘acc_test_func’:
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:96:10: warning: implicit declaration of function ‘bswap_16’ [-Wimplicit-function-declaration]
   (void) bswap_16(1);
          ^~~~~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:97:10: warning: implicit declaration of function ‘bswap_32’ [-Wimplicit-function-declaration]
   (void) bswap_32(1);
          ^~~~~~~~

 * --> exit 1 (len 942)
 */
/*
 * -DACC_DEF_BYTESWAP_INCLUDE_sys_types_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:89:3: error: #error bswap_16 not defined
 # error bswap_16 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:92:3: error: #error bswap_32 not defined
 # error bswap_32 not defined
   ^~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h: In function ‘acc_test_func’:
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:96:10: warning: implicit declaration of function ‘bswap_16’ [-Wimplicit-function-declaration]
   (void) bswap_16(1);
          ^~~~~~~~
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteswap_include.h:97:10: warning: implicit declaration of function ‘bswap_32’ [-Wimplicit-function-declaration]
   (void) bswap_32(1);
          ^~~~~~~~

 * --> exit 1 (len 942)
 */
/*
 * -DACC_DEF_BYTESWAP_INCLUDE_mybyteswap

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C

 * --> exit 0 (len 88)
 */

/********************************************************************/

#define ACC_DEF_BYTESWAP_INCLUDE_byteswap_h 1

/********************************************************************/

#endif/*__AUTO_DEF__BYTESWAP_INCLUDE_HH__*/
