/*********************************************************************
 *
 * This file is autogenerated by /u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/lu_common/make_acc_auto_def.sh
 *
 * Editing is useless.
 *
 *********************************************************************
 *
 * Input file:    /u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteorder_include.h
 * Basename:      BYTEORDER_INCLUDE
 * Compiler:      g++
 * Compiler args: -I. -DUNPACKERNAME=201902_s473 -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/file_input -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/file_input/lmd_struct -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/threading -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/lu_common -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def -ansi -Wall -W -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wwrite-strings -Wconversion -g -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_LIMIT_MACROS -DHAVE_TEE -Igen_201902_s473 -DGENDIR="gen_201902_s473" -DUSE_EXT_WRITER= -DUSING_EXT_WRITER= -DEXT_WRITER_PREFIX="/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/hbook/" -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/hbook -DUSE_CURSES=1 -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/watcher -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/u/land/fake_cvmfs/upexps/201902_s473/../landdaq_/vidsel/siderem -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/dets/sst -std=c++11 -DCONTROL_INCLUDE -I./../land_common -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/dets/sst -DHAVE_THREAD_LOCAL_STORAGE -pthread -DUSE_PTHREAD=1 -DHAVE_PTHREAD -DUSE_LMD_INPUT=1 -DUSE_LMD_OUTPUT_TCP -I/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/mapcalib
 *
 ********************************************************************/

#ifndef __AUTO_DEF__BYTEORDER_INCLUDE_HH__
#define __AUTO_DEF__BYTEORDER_INCLUDE_HH__

/*
 * Option: byteorder_h
 * Option: bsd_bsd_byteorder_h
 * Option: endian_h
 * Option: sys_endian_h
 * Option: machine_endian_h
 * Option: machine_byte_order_h
 * Option: sys_types_h_stdint_h
 */
/*
 * -DACC_DEF_BYTEORDER_INCLUDE_byteorder_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteorder_include.h:29:24: fatal error: byteorder.h: No such file or directory
 # include "byteorder.h"
                        ^
compilation terminated.

 * --> exit 1 (len 299)
 */
/*
 * -DACC_DEF_BYTEORDER_INCLUDE_bsd_bsd_byteorder_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteorder_include.h:32:32: fatal error: bsd/bsd_byteorder.h: No such file or directory
 # include "bsd/bsd_byteorder.h"
                                ^
compilation terminated.

 * --> exit 1 (len 323)
 */
/*
 * -DACC_DEF_BYTEORDER_INCLUDE_endian_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C

 * --> exit 0 (len 88)
 */
/*
 * -DACC_DEF_BYTEORDER_INCLUDE_sys_endian_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteorder_include.h:38:25: fatal error: sys/endian.h: No such file or directory
 # include "sys/endian.h"
                         ^
compilation terminated.

 * --> exit 1 (len 302)
 */
/*
 * -DACC_DEF_BYTEORDER_INCLUDE_machine_endian_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteorder_include.h:41:29: fatal error: machine/endian.h: No such file or directory
 # include "machine/endian.h"
                             ^
compilation terminated.

 * --> exit 1 (len 314)
 */
/*
 * -DACC_DEF_BYTEORDER_INCLUDE_machine_byte_order_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteorder_include.h:68:3: error: #error BYTE_ORDER not defined
 # error BYTE_ORDER not defined
   ^~~~~

 * --> exit 1 (len 249)
 */
/*
 * -DACC_DEF_BYTEORDER_INCLUDE_sys_types_h_stdint_h

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
/u/land/opt/ucesb/opt_x86_64-linux-gnu_4.7/ucesb/acc_def/byteorder_include.h:68:3: error: #error BYTE_ORDER not defined
 # error BYTE_ORDER not defined
   ^~~~~

 * --> exit 1 (len 249)
 */

/********************************************************************/

#define ACC_DEF_BYTEORDER_INCLUDE_endian_h 1

/********************************************************************/

#endif/*__AUTO_DEF__BYTEORDER_INCLUDE_HH__*/
