/** BEGIN_MIRROR_STRUCT ************************************************
 *
 * Mirror (1 to 1) structure.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_mirror_define.hh"

#ifndef USER_DEF_raw_event_TIMESTAMP_LOS_WR
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_LOS_WR)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,4);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[4]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_LOS_WR);
};
#endif//USER_DEF_raw_event_TIMESTAMP_LOS_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_LOS
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_LOS)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(ID);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ID);
  STRUCT_MIRROR_ITEM_CTRL(WR);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_LOS_WR) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(WR);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_LOS);
};
#endif//USER_DEF_raw_event_TIMESTAMP_LOS

#ifndef USER_DEF_raw_event_TIMESTAMP_SCITWO_WR
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_SCITWO_WR)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,4);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[4]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_SCITWO_WR);
};
#endif//USER_DEF_raw_event_TIMESTAMP_SCITWO_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_SCITWO
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_SCITWO)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(ID);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ID);
  STRUCT_MIRROR_ITEM_CTRL(WR);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_SCITWO_WR) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(WR);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_SCITWO);
};
#endif//USER_DEF_raw_event_TIMESTAMP_SCITWO

#ifndef USER_DEF_raw_event_TIMESTAMP_SCIEIGHT_WR
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_SCIEIGHT_WR)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,4);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[4]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_SCIEIGHT_WR);
};
#endif//USER_DEF_raw_event_TIMESTAMP_SCIEIGHT_WR

#ifndef USER_DEF_raw_event_TIMESTAMP_SCIEIGHT
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP_SCIEIGHT)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(ID);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ID);
  STRUCT_MIRROR_ITEM_CTRL(WR);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_SCIEIGHT_WR) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(WR);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP_SCIEIGHT);
};
#endif//USER_DEF_raw_event_TIMESTAMP_SCIEIGHT

#ifndef USER_DEF_raw_event_TIMESTAMP
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TIMESTAMP)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(LOS);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_LOS) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LOS);
  STRUCT_MIRROR_ITEM_CTRL(SCITWO);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_SCITWO) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SCITWO);
  STRUCT_MIRROR_ITEM_CTRL(SCIEIGHT);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP_SCIEIGHT) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SCIEIGHT);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TIMESTAMP);
};
#endif//USER_DEF_raw_event_TIMESTAMP

#ifndef USER_DEF_raw_event_LOS
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_LOS)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(VTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,32> STRUCT_MIRROR_NAME(VTF);
  STRUCT_MIRROR_ITEM_CTRL(VTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),8,32> STRUCT_MIRROR_NAME(VTC);
  STRUCT_MIRROR_ITEM_CTRL(MT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),8,32> STRUCT_MIRROR_NAME(MT);
  STRUCT_MIRROR_ITEM_CTRL(TTFL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,32> STRUCT_MIRROR_NAME(TTFL);
  STRUCT_MIRROR_ITEM_CTRL(TTFT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,32> STRUCT_MIRROR_NAME(TTFT);
  STRUCT_MIRROR_ITEM_CTRL(TTCL);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,32> STRUCT_MIRROR_NAME(TTCL);
  STRUCT_MIRROR_ITEM_CTRL(TTCT);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,32> STRUCT_MIRROR_NAME(TTCT);
  STRUCT_MIRROR_FCNS_DECL(raw_event_LOS);
};
#endif//USER_DEF_raw_event_LOS

#ifndef USER_DEF_raw_event_SCITWO
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SCITWO)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(VTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,32> STRUCT_MIRROR_NAME(VTF);
  STRUCT_MIRROR_ITEM_CTRL(VTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),8,32> STRUCT_MIRROR_NAME(VTC);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SCITWO);
};
#endif//USER_DEF_raw_event_SCITWO

#ifndef USER_DEF_raw_event_SCIEIGHT
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SCIEIGHT)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(VTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),8,32> STRUCT_MIRROR_NAME(VTF);
  STRUCT_MIRROR_ITEM_CTRL(VTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),8,32> STRUCT_MIRROR_NAME(VTC);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SCIEIGHT);
};
#endif//USER_DEF_raw_event_SCIEIGHT

#ifndef USER_DEF_raw_event_FIBONEA
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FIBONEA)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TMLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMLC);
  STRUCT_MIRROR_ITEM_CTRL(TMLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMLF);
  STRUCT_MIRROR_ITEM_CTRL(TMTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMTC);
  STRUCT_MIRROR_ITEM_CTRL(TMTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMTF);
  STRUCT_MIRROR_ITEM_CTRL(TSLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),1,64> STRUCT_MIRROR_NAME(TSLC);
  STRUCT_MIRROR_ITEM_CTRL(TSLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),1,64> STRUCT_MIRROR_NAME(TSLF);
  STRUCT_MIRROR_ITEM_CTRL(TSTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),1,64> STRUCT_MIRROR_NAME(TSTC);
  STRUCT_MIRROR_ITEM_CTRL(TSTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),1,64> STRUCT_MIRROR_NAME(TSTF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FIBONEA);
};
#endif//USER_DEF_raw_event_FIBONEA

#ifndef USER_DEF_raw_event_FIBONEB
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_FIBONEB)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TMLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMLC);
  STRUCT_MIRROR_ITEM_CTRL(TMLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMLF);
  STRUCT_MIRROR_ITEM_CTRL(TMTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMTC);
  STRUCT_MIRROR_ITEM_CTRL(TMTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TMTF);
  STRUCT_MIRROR_ITEM_CTRL(TSLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),1,64> STRUCT_MIRROR_NAME(TSLC);
  STRUCT_MIRROR_ITEM_CTRL(TSLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),1,64> STRUCT_MIRROR_NAME(TSLF);
  STRUCT_MIRROR_ITEM_CTRL(TSTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),1,64> STRUCT_MIRROR_NAME(TSTC);
  STRUCT_MIRROR_ITEM_CTRL(TSTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),1,64> STRUCT_MIRROR_NAME(TSTF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_FIBONEB);
};
#endif//USER_DEF_raw_event_FIBONEB

#ifndef USER_DEF_raw_event_SFIB
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SFIB)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TTLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TTLC);
  STRUCT_MIRROR_ITEM_CTRL(BTLC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(BTLC);
  STRUCT_MIRROR_ITEM_CTRL(TTLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TTLF);
  STRUCT_MIRROR_ITEM_CTRL(BTLF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(BTLF);
  STRUCT_MIRROR_ITEM_CTRL(TTTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TTTC);
  STRUCT_MIRROR_ITEM_CTRL(BTTC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(BTTC);
  STRUCT_MIRROR_ITEM_CTRL(TTTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(TTTF);
  STRUCT_MIRROR_ITEM_CTRL(BTTF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),256,64> STRUCT_MIRROR_NAME(BTTF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SFIB);
};
#endif//USER_DEF_raw_event_SFIB

#ifndef USER_DEF_raw_event_NN_WR
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_WR)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(ID);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ID);
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,4);
  STRUCT_MIRROR_TYPE(DATA16) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[4]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_WR);
};
#endif//USER_DEF_raw_event_NN_WR

#ifndef USER_DEF_raw_event_NN_P_tcl_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tcl_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(B);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),50,200> STRUCT_MIRROR_NAME(B);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tcl_T);
};
#endif//USER_DEF_raw_event_NN_P_tcl_T

#ifndef USER_DEF_raw_event_NN_P_tcl
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tcl)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tcl_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tcl);
};
#endif//USER_DEF_raw_event_NN_P_tcl

#ifndef USER_DEF_raw_event_NN_P_tfl_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tfl_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(B);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),50,200> STRUCT_MIRROR_NAME(B);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tfl_T);
};
#endif//USER_DEF_raw_event_NN_P_tfl_T

#ifndef USER_DEF_raw_event_NN_P_tfl
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tfl)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tfl_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tfl);
};
#endif//USER_DEF_raw_event_NN_P_tfl

#ifndef USER_DEF_raw_event_NN_P_tct_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tct_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(B);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),50,200> STRUCT_MIRROR_NAME(B);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tct_T);
};
#endif//USER_DEF_raw_event_NN_P_tct_T

#ifndef USER_DEF_raw_event_NN_P_tct
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tct)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tct_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tct);
};
#endif//USER_DEF_raw_event_NN_P_tct

#ifndef USER_DEF_raw_event_NN_P_tft_T
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tft_T)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(B);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),50,200> STRUCT_MIRROR_NAME(B);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tft_T);
};
#endif//USER_DEF_raw_event_NN_P_tft_T

#ifndef USER_DEF_raw_event_NN_P_tft
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P_tft)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(T__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tft_T) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(T[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P_tft);
};
#endif//USER_DEF_raw_event_NN_P_tft

#ifndef USER_DEF_raw_event_NN_P
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN_P)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(tcl);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tcl) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tcl);
  STRUCT_MIRROR_ITEM_CTRL(tfl);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tfl) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tfl);
  STRUCT_MIRROR_ITEM_CTRL(tct);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tct) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tct);
  STRUCT_MIRROR_ITEM_CTRL(tft);
  STRUCT_MIRROR_TYPE(raw_event_NN_P_tft) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tft);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN_P);
};
#endif//USER_DEF_raw_event_NN_P

#ifndef USER_DEF_raw_event_NN
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_NN)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(WR);
  STRUCT_MIRROR_TYPE(raw_event_NN_WR) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(WR);
  STRUCT_MIRROR_ITEM_CTRL(P);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(P__i0,,16);
  STRUCT_MIRROR_TYPE(raw_event_NN_P) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(P[16]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_NN);
};
#endif//USER_DEF_raw_event_NN

#ifndef USER_DEF_raw_event_MUSIC
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_MUSIC)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),8,10> STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),8,10> STRUCT_MIRROR_NAME(T);
  STRUCT_MIRROR_ITEM_CTRL(TREF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),2,10> STRUCT_MIRROR_NAME(TREF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_MUSIC);
};
#endif//USER_DEF_raw_event_MUSIC

#ifndef USER_DEF_raw_event_SOFSCI
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SOFSCI)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),3,10> STRUCT_MIRROR_NAME(TF);
  STRUCT_MIRROR_ITEM_CTRL(TC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),3,10> STRUCT_MIRROR_NAME(TC);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SOFSCI);
};
#endif//USER_DEF_raw_event_SOFSCI

#ifndef USER_DEF_raw_event_SOFTWIM_S
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SOFTWIM_S)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),16,10> STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_ITEM_CTRL(T);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),16,10> STRUCT_MIRROR_NAME(T);
  STRUCT_MIRROR_ITEM_CTRL(TREF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),STRUCT_MIRROR_TEMPLATE_ARG(DATA16_OVERFLOW),2,10> STRUCT_MIRROR_NAME(TREF);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SOFTWIM_S);
};
#endif//USER_DEF_raw_event_SOFTWIM_S

#ifndef USER_DEF_raw_event_SOFTWIM
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SOFTWIM)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(S);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(S__i0,,1);
  STRUCT_MIRROR_TYPE(raw_event_SOFTWIM_S) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(S[1]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SOFTWIM);
};
#endif//USER_DEF_raw_event_SOFTWIM

#ifndef USER_DEF_raw_event_SOFTOFW_P
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SOFTOFW_P)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(TF);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),2,10> STRUCT_MIRROR_NAME(TF);
  STRUCT_MIRROR_ITEM_CTRL(TC);
  STRUCT_MIRROR_TYPE(raw_array_multi_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),2,10> STRUCT_MIRROR_NAME(TC);
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(E__i0,,2);
  STRUCT_MIRROR_TYPE(DATA14) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(E[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SOFTOFW_P);
};
#endif//USER_DEF_raw_event_SOFTOFW_P

#ifndef USER_DEF_raw_event_SOFTOFW
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SOFTOFW)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(P);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(P__i0,,28);
  STRUCT_MIRROR_TYPE(raw_event_SOFTOFW_P) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(P[28]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SOFTOFW);
};
#endif//USER_DEF_raw_event_SOFTOFW

#ifndef USER_DEF_raw_event_SOFMWPC_Plane
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SOFMWPC_Plane)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(Q);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA12),STRUCT_MIRROR_TEMPLATE_ARG(DATA12),288> STRUCT_MIRROR_NAME(Q);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SOFMWPC_Plane);
};
#endif//USER_DEF_raw_event_SOFMWPC_Plane

#ifndef USER_DEF_raw_event_SOFMWPC
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SOFMWPC)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(Plane);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(Plane__i0,,3);
  STRUCT_MIRROR_TYPE(raw_event_SOFMWPC_Plane) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(Plane[3]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SOFMWPC);
};
#endif//USER_DEF_raw_event_SOFMWPC

#ifndef USER_DEF_raw_event_SST
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SST)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SST);
};
#endif//USER_DEF_raw_event_SST

#ifndef USER_DEF_raw_event_CALIFA
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_CALIFA)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(ENE);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),2048> STRUCT_MIRROR_NAME(ENE);
  STRUCT_MIRROR_ITEM_CTRL(TSLSB);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),2048> STRUCT_MIRROR_NAME(TSLSB);
  STRUCT_MIRROR_ITEM_CTRL(TSMSB);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),2048> STRUCT_MIRROR_NAME(TSMSB);
  STRUCT_MIRROR_ITEM_CTRL(NF);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),2048> STRUCT_MIRROR_NAME(NF);
  STRUCT_MIRROR_ITEM_CTRL(NS);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA16),STRUCT_MIRROR_TEMPLATE_ARG(DATA16),2048> STRUCT_MIRROR_NAME(NS);
  STRUCT_MIRROR_FCNS_DECL(raw_event_CALIFA);
};
#endif//USER_DEF_raw_event_CALIFA

#ifndef USER_DEF_raw_event
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event) : public STRUCT_MIRROR_BASE(raw_event_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_event_base);
  STRUCT_MIRROR_ITEM_CTRL(TIMESTAMP);
  STRUCT_MIRROR_TYPE(raw_event_TIMESTAMP) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TIMESTAMP);
  STRUCT_MIRROR_ITEM_CTRL(LOS);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(LOS__i0,,2);
  STRUCT_MIRROR_TYPE(raw_event_LOS) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LOS[2]);
  STRUCT_MIRROR_ITEM_CTRL(SCITWO);
  STRUCT_MIRROR_TYPE(raw_event_SCITWO) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SCITWO);
  STRUCT_MIRROR_ITEM_CTRL(SCIEIGHT);
  STRUCT_MIRROR_TYPE(raw_event_SCIEIGHT) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SCIEIGHT);
  STRUCT_MIRROR_ITEM_CTRL(FIBONEA);
  STRUCT_MIRROR_TYPE(raw_event_FIBONEA) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FIBONEA);
  STRUCT_MIRROR_ITEM_CTRL(FIBONEB);
  STRUCT_MIRROR_TYPE(raw_event_FIBONEB) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(FIBONEB);
  STRUCT_MIRROR_ITEM_CTRL(SFIB);
  STRUCT_MIRROR_TYPE(raw_event_SFIB) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SFIB);
  STRUCT_MIRROR_ITEM_CTRL(NN);
  STRUCT_MIRROR_TYPE(raw_event_NN) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(NN);
  STRUCT_MIRROR_ITEM_CTRL(SAMP);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),512> STRUCT_MIRROR_NAME(SAMP);
  STRUCT_MIRROR_ITEM_CTRL(MUSIC);
  STRUCT_MIRROR_TYPE(raw_event_MUSIC) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(MUSIC);
  STRUCT_MIRROR_ITEM_CTRL(SOFSCI);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(SOFSCI__i0,,1);
  STRUCT_MIRROR_TYPE(raw_event_SOFSCI) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SOFSCI[1]);
  STRUCT_MIRROR_ITEM_CTRL(SOFTWIM);
  STRUCT_MIRROR_TYPE(raw_event_SOFTWIM) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SOFTWIM);
  STRUCT_MIRROR_ITEM_CTRL(SOFTOFW);
  STRUCT_MIRROR_TYPE(raw_event_SOFTOFW) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SOFTOFW);
  STRUCT_MIRROR_ITEM_CTRL(SOFMWPC);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(SOFMWPC__i0,,4);
  STRUCT_MIRROR_TYPE(raw_event_SOFMWPC) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SOFMWPC[4]);
  STRUCT_MIRROR_ITEM_CTRL(SST);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(SST__i0,,6);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(raw_event_SST),STRUCT_MIRROR_TEMPLATE_ARG(raw_event_SST),1024> STRUCT_MIRROR_NAME(SST[6]);
  STRUCT_MIRROR_ITEM_CTRL(CALIFA);
  STRUCT_MIRROR_TYPE(raw_event_CALIFA) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(CALIFA);
  STRUCT_MIRROR_FCNS_DECL(raw_event);
};
#endif//USER_DEF_raw_event

#ifndef USER_DEF_raw_sticky
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_sticky) : public STRUCT_MIRROR_BASE(raw_sticky_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_sticky_base);
  STRUCT_MIRROR_FCNS_DECL(raw_sticky);
};
#endif//USER_DEF_raw_sticky

#include "gen/default_mirror_undef.hh"


/** END_MIRROR_STRUCT *************************************************/
