/** BEGIN_MIRROR_STRUCT ************************************************
 *
 * Mirror (1 to 1) structure.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_mirror_define.hh"

#ifndef USER_DEF_cal_event_MW
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(cal_event_MW)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(AN);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(AN);
  STRUCT_MIRROR_ITEM_CTRL(XR);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(XR);
  STRUCT_MIRROR_ITEM_CTRL(XL);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(XL);
  STRUCT_MIRROR_ITEM_CTRL(YU);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(YU);
  STRUCT_MIRROR_ITEM_CTRL(YD);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(YD);
  STRUCT_MIRROR_FCNS_DECL(cal_event_MW);
};
#endif//USER_DEF_cal_event_MW

#ifndef USER_DEF_cal_event_TOF
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(cal_event_TOF)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(L);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(L);
  STRUCT_MIRROR_ITEM_CTRL(R);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(R);
  STRUCT_MIRROR_FCNS_DECL(cal_event_TOF);
};
#endif//USER_DEF_cal_event_TOF

#ifndef USER_DEF_cal_event_TPC
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(cal_event_TPC)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(A);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(A__i0,,4);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(A[4]);
  STRUCT_MIRROR_ITEM_CTRL(AR);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(AR__i0,,2);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(AR[2]);
  STRUCT_MIRROR_ITEM_CTRL(AL);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(AL__i0,,2);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(AL[2]);
  STRUCT_MIRROR_ITEM_CTRL(DT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(DT__i0,,4);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(DT[4]);
  STRUCT_MIRROR_ITEM_CTRL(LT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(LT__i0,,2);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LT[2]);
  STRUCT_MIRROR_ITEM_CTRL(RT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(RT__i0,,2);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(RT[2]);
  STRUCT_MIRROR_FCNS_DECL(cal_event_TPC);
};
#endif//USER_DEF_cal_event_TPC

#ifndef USER_DEF_cal_event_SC
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(cal_event_SC)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(DT);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(DT);
  STRUCT_MIRROR_ITEM_CTRL(DEL);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(DEL);
  STRUCT_MIRROR_ITEM_CTRL(DER);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(DER);
  STRUCT_MIRROR_FCNS_DECL(cal_event_SC);
};
#endif//USER_DEF_cal_event_SC

#ifndef USER_DEF_cal_event
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(cal_event) : public STRUCT_MIRROR_BASE(cal_event_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(cal_event_base);
  STRUCT_MIRROR_ITEM_CTRL(MW);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(MW__i0,,2);
  STRUCT_MIRROR_TYPE(cal_event_MW) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(MW[2]);
  STRUCT_MIRROR_ITEM_CTRL(TOF);
  STRUCT_MIRROR_TYPE(cal_event_TOF) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TOF);
  STRUCT_MIRROR_ITEM_CTRL(TPC);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(TPC__i0,,3);
  STRUCT_MIRROR_TYPE(cal_event_TPC) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TPC[3]);
  STRUCT_MIRROR_ITEM_CTRL(SC);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(SC__i0,,3);
  STRUCT_MIRROR_TYPE(cal_event_SC) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(SC[3]);
  STRUCT_MIRROR_FCNS_DECL(cal_event);
};
#endif//USER_DEF_cal_event

#include "gen/default_mirror_undef.hh"


/** END_MIRROR_STRUCT *************************************************/
