/** BEGIN_FUNCTION_CALL_PER_MEMBER *************************************
 *
 * Recursive function calls per member.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_fcncall_define.hh"

#ifndef USER_DEF_raw_event_MW
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_MW)::FCNCALL_NAME(raw_event_MW)
{
  FCNCALL_INIT;
  // DATA12_OVERFLOW AN;
  {
  FCNCALL_SUBNAME("AN");
  { FCNCALL_CALL_CTRL_WRAP(AN,AN.FCNCALL_CALL(AN)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW XR;
  {
  FCNCALL_SUBNAME("XR");
  { FCNCALL_CALL_CTRL_WRAP(XR,XR.FCNCALL_CALL(XR)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW XL;
  {
  FCNCALL_SUBNAME("XL");
  { FCNCALL_CALL_CTRL_WRAP(XL,XL.FCNCALL_CALL(XL)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW YU;
  {
  FCNCALL_SUBNAME("YU");
  { FCNCALL_CALL_CTRL_WRAP(YU,YU.FCNCALL_CALL(YU)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW YD;
  {
  FCNCALL_SUBNAME("YD");
  { FCNCALL_CALL_CTRL_WRAP(YD,YD.FCNCALL_CALL(YD)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_MW

#ifndef USER_DEF_raw_event_TOF
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TOF)::FCNCALL_NAME(raw_event_TOF)
{
  FCNCALL_INIT;
  // DATA12_OVERFLOW L;
  {
  FCNCALL_SUBNAME("L");
  { FCNCALL_CALL_CTRL_WRAP(L,L.FCNCALL_CALL(L)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW R;
  {
  FCNCALL_SUBNAME("R");
  { FCNCALL_CALL_CTRL_WRAP(R,R.FCNCALL_CALL(R)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TOF

#ifndef USER_DEF_raw_event_TPC
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_TPC)::FCNCALL_NAME(raw_event_TPC)
{
  FCNCALL_INIT;
  // DATA12_OVERFLOW A[4];
  {
  FCNCALL_SUBNAME("A");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(A__i0,,__i0,A[__i0].FCNCALL_CALL(A[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW AR[2];
  {
  FCNCALL_SUBNAME("AR");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(AR__i0,,__i0,AR[__i0].FCNCALL_CALL(AR[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW AL[2];
  {
  FCNCALL_SUBNAME("AL");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(AL__i0,,__i0,AL[__i0].FCNCALL_CALL(AL[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW DT[4];
  {
  FCNCALL_SUBNAME("DT");
  FCNCALL_FOR(__i0,4)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(DT__i0,,__i0,DT[__i0].FCNCALL_CALL(DT[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW LT[2];
  {
  FCNCALL_SUBNAME("LT");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(LT__i0,,__i0,LT[__i0].FCNCALL_CALL(LT[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW RT[2];
  {
  FCNCALL_SUBNAME("RT");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(RT__i0,,__i0,RT[__i0].FCNCALL_CALL(RT[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_TPC

#ifndef USER_DEF_raw_event_SC
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event_SC)::FCNCALL_NAME(raw_event_SC)
{
  FCNCALL_INIT;
  // DATA12_OVERFLOW DT;
  {
  FCNCALL_SUBNAME("DT");
  { FCNCALL_CALL_CTRL_WRAP(DT,DT.FCNCALL_CALL(DT)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW DEL;
  {
  FCNCALL_SUBNAME("DEL");
  { FCNCALL_CALL_CTRL_WRAP(DEL,DEL.FCNCALL_CALL(DEL)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA12_OVERFLOW DER;
  {
  FCNCALL_SUBNAME("DER");
  { FCNCALL_CALL_CTRL_WRAP(DER,DER.FCNCALL_CALL(DER)); }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event_SC

#ifndef USER_DEF_raw_event
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_event)::FCNCALL_NAME(raw_event)
{
  FCNCALL_INIT;
  FCNCALL_CALL_CTRL_WRAP(raw_event_base,FCNCALL_CLASS_NAME(raw_event_base)::FCNCALL_CALL_BASE());
  // raw_event_MW MW[2];
  {
  FCNCALL_SUBNAME("MW");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(MW__i0,,__i0,MW[__i0].FCNCALL_CALL(MW[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 PATTERN;
  {
  FCNCALL_SUBNAME("PATTERN");
  { FCNCALL_CALL_CTRL_WRAP(PATTERN,PATTERN.FCNCALL_CALL(PATTERN)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 MULTIP;
  {
  FCNCALL_SUBNAME("MULTIP");
  { FCNCALL_CALL_CTRL_WRAP(MULTIP,MULTIP.FCNCALL_CALL(MULTIP)); }
  FCNCALL_SUBNAME_END;
  }
  // DATA32 SCALER[2][18];
  {
  FCNCALL_SUBNAME("SCALER");
  FCNCALL_FOR(__i0,2)
  {
    FCNCALL_SUBINDEX(__i0);
    FCNCALL_FOR(__i1,18)
    {
      FCNCALL_SUBINDEX(__i1);
      { FCNCALL_CALL_CTRL_WRAP_ARRAY(SCALER__i0__i1,[__i0],__i1,SCALER[__i0][__i1].FCNCALL_CALL(SCALER[__i0][__i1])); }
      FCNCALL_SUBINDEX_END(__i1);
    }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TOF TOF;
  {
  FCNCALL_SUBNAME("TOF");
  { FCNCALL_CALL_CTRL_WRAP(TOF,TOF.FCNCALL_CALL(TOF)); }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_TPC TPC[3];
  {
  FCNCALL_SUBNAME("TPC");
  FCNCALL_FOR(__i0,3)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(TPC__i0,,__i0,TPC[__i0].FCNCALL_CALL(TPC[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  // raw_event_SC SC[3];
  {
  FCNCALL_SUBNAME("SC");
  FCNCALL_FOR(__i0,3)
  {
    FCNCALL_SUBINDEX(__i0);
    { FCNCALL_CALL_CTRL_WRAP_ARRAY(SC__i0,,__i0,SC[__i0].FCNCALL_CALL(SC[__i0])); }
    FCNCALL_SUBINDEX_END(__i0);
  }
  FCNCALL_SUBNAME_END;
  }
  FCNCALL_RET;
}
#endif//USER_DEF_raw_event

#ifndef USER_DEF_raw_sticky
FCNCALL_TEMPLATE
FCNCALL_RET_TYPE FCNCALL_CLASS_NAME(raw_sticky)::FCNCALL_NAME(raw_sticky)
{
  FCNCALL_INIT;
  FCNCALL_CALL_CTRL_WRAP(raw_sticky_base,FCNCALL_CLASS_NAME(raw_sticky_base)::FCNCALL_CALL_BASE());
  FCNCALL_RET;
}
#endif//USER_DEF_raw_sticky

#include "gen/default_fcncall_undef.hh"


/** END_FUNCTION_CALL_PER_MEMBER **************************************/
