/** BEGIN_MIRROR_DECL_STRUCT *******************************************
 *
 * Mirror structure names.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_mirror_define.hh"

STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(EMPTY_32BIT_WORD_V775_FRS);

STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(EMPTY_32BIT_WORD_V830_FRS);

STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(VME_CAEN_V259_FRS);

STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(VME_CAEN_V775_FRS);

STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(VME_CAEN_V830_FRS);

STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(FRS_CRATE);

STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(TPC_CRATE);

STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(unpack_event);

STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(unpack_sticky_event);

#include "gen/default_mirror_undef.hh"


/** END_MIRROR_DECL_STRUCT ********************************************/
