/** BEGIN_MIRROR_STRUCT ************************************************
 *
 * Mirror (1 to 1) structure.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_mirror_define.hh"

#ifndef USER_DEF_hit_mul
STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(hit_mul)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(x);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(x);
  STRUCT_MIRROR_ITEM_CTRL(y);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(y);
  STRUCT_MIRROR_ITEM_CTRL(sumx);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(sumx);
  STRUCT_MIRROR_ITEM_CTRL(sumy);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(sumy);
  STRUCT_MIRROR_FCNS_DECL(hit_mul);
};
#endif//USER_DEF_hit_mul

#ifndef USER_DEF_hit_tpc
STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(hit_tpc)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(x1);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(x1);
  STRUCT_MIRROR_ITEM_CTRL(x2);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(x2);
  STRUCT_MIRROR_ITEM_CTRL(y);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(y);
  STRUCT_MIRROR_ITEM_CTRL(sumx);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(sumx__i0,,4);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(sumx__i0__i1,[4],2);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(sumx[4][2]);
  STRUCT_MIRROR_FCNS_DECL(hit_tpc);
};
#endif//USER_DEF_hit_tpc

#ifndef USER_DEF_hit_sci
STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(hit_sci)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(de);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(de);
  STRUCT_MIRROR_ITEM_CTRL(dt);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(dt);
  STRUCT_MIRROR_FCNS_DECL(hit_sci);
};
#endif//USER_DEF_hit_sci

#ifndef USER_DEF_hit_tof
STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(hit_tof)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(s2s3);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(s2s3);
  STRUCT_MIRROR_FCNS_DECL(hit_tof);
};
#endif//USER_DEF_hit_tof

#ifndef USER_DEF_hit_angle
STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(hit_angle)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(pos);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(pos__i0,,2);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(pos__i0__i1,[2],2);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(pos[2][2]);
  STRUCT_MIRROR_ITEM_CTRL(at_s);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(at_s__i0,,2);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(at_s[2]);
  STRUCT_MIRROR_FCNS_DECL(hit_angle);
};
#endif//USER_DEF_hit_angle

#ifndef USER_DEF_hit_track
STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(hit_track)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(xtr);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(xtr);
  STRUCT_MIRROR_FCNS_DECL(hit_track);
};
#endif//USER_DEF_hit_track

#ifndef USER_DEF_hit_id
STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(hit_id)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(q);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(q__i0,,2);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(q[2]);
  STRUCT_MIRROR_ITEM_CTRL(rho);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(rho);
  STRUCT_MIRROR_ITEM_CTRL(brho);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(brho);
  STRUCT_MIRROR_ITEM_CTRL(beta);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(beta);
  STRUCT_MIRROR_ITEM_CTRL(gamma);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(gamma);
  STRUCT_MIRROR_ITEM_CTRL(aoq);
  STRUCT_MIRROR_TYPE(float) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(aoq);
  STRUCT_MIRROR_FCNS_DECL(hit_id);
};
#endif//USER_DEF_hit_id

#ifndef USER_DEF_hit_event
STRUCT_MIRROR_TEMPLATE
struct STRUCT_MIRROR_STRUCT(hit_event)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(sc);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(sc__i0,,3);
  STRUCT_MIRROR_TYPE(hit_sci) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(sc[3]);
  STRUCT_MIRROR_ITEM_CTRL(tof);
  STRUCT_MIRROR_TYPE(hit_tof) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tof);
  STRUCT_MIRROR_ITEM_CTRL(mw);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(mw__i0,,2);
  STRUCT_MIRROR_TYPE(hit_mul) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(mw[2]);
  STRUCT_MIRROR_ITEM_CTRL(tpc);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(tpc__i0,,3);
  STRUCT_MIRROR_TYPE(hit_tpc) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(tpc[3]);
  STRUCT_MIRROR_ITEM_CTRL(ang);
  STRUCT_MIRROR_TYPE(hit_angle) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ang);
  STRUCT_MIRROR_ITEM_CTRL(s);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(s__i0,,2);
  STRUCT_MIRROR_TYPE(hit_track) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(s[2]);
  STRUCT_MIRROR_ITEM_CTRL(s3);
  STRUCT_MIRROR_TYPE(hit_id) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(s3);
  STRUCT_MIRROR_FCNS_DECL(hit_event);
};
#endif//USER_DEF_hit_event

#include "gen/default_mirror_undef.hh"


/** END_MIRROR_STRUCT *************************************************/
