#########################################################
# Specify the name of the target executable

TARGETS:=frs_s341

#########################################################
# Include common Makefile

include ../makefile_common.mk
