SIGNAL(ZERO_SUPPRESS:CALIFA_ENE_1);
SIGNAL(ZERO_SUPPRESS:CALIFA_TSLSB_1);
SIGNAL(ZERO_SUPPRESS:CALIFA_TSMSB_1);
SIGNAL(ZERO_SUPPRESS:CALIFA_NF_1);
SIGNAL(ZERO_SUPPRESS:CALIFA_NS_1);

// ENERGY SIGNAL
SIGNAL(CALIFA_ENE_1,califa.febex3.energy[0],CALIFA_ENE_2048,califa.febex3.energy[2047],DATA16);

// TIME STAMP - least significant bit
SIGNAL(CALIFA_TSLSB_1,califa.febex3.ts_lsb[0],CALIFA_TSLSB_2048,califa.febex3.ts_lsb[2047],DATA32);

// TIME STAMP MOST SIGNIFICANT BITS
SIGNAL(CALIFA_TSMSB_1,califa.febex3.ts_msb[0],CALIFA_TSMSB_2048,califa.febex3.ts_msb[2047],DATA32);

// FAST ENERGY INTEGRAL
SIGNAL(CALIFA_NF_1,califa.febex3.n_f[0],CALIFA_NF_2048,califa.febex3.n_f[2047],DATA16);

// SLOW ENERGY INTEGRAL
SIGNAL(CALIFA_NS_1,califa.febex3.n_s[0],CALIFA_NS_2048,califa.febex3.n_s[2047],DATA16);
