// -*- C++ -*-

#define SUBEVENT_START_STOP_ACQ     35
#define SUBEVENT_CAMAC              34
#define SUBEVENT_CAMAC_TCAL         9934
#define SUBEVENT_CAMAC_SCALERS      3100
#define SUBEVENT_CAMAC_CONVERTERS   3200
#define SUBEVENT_CAMAC_TCAL_INFO    3199
#define SUBEVENT_CAMAC_POS_PILEUP   3500 // leave 2 if they were ever used...

#define SUBEVENT_FASTBUS_ERROR          31
#define SUBEVENT_FASTBUS_ERROR_INFO     3100
#define SUBEVENT_FASTBUS_ERROR_INFO3131 3131

#define SUBEVENT_FASTBUS1           32
#define SUBEVENT_FASTBUS2           32
#define SUBEVENT_FASTBUS            32
#define SUBEVENT_FASTBUS_DATA1      3100
#define SUBEVENT_FASTBUS_DATA3130   3130

#define SUBEVENT_VME                88
#define SUBEVENT_VME_DATA8800       8800

#define SUBEVENT_SST                82
#define SUBEVENT_SST_DATA8200       8200

#define SUBEVENT_CROS3              85
#define SUBEVENT_CROS3_DATA         8500
#define SUBEVENT_CROS3_DATA_REWRITE 8510
