#########################################################
# Specify the name of the target executable

TARGETS:=201904_s454

#########################################################
# Include common Makefile

include ../makefile_common.mk
