// TRLO master white rabbit timestamp
SIGNAL(TIMESTAMP_MASTER_ID, master_ts.ts100.subsystem_id, DATA12);
SIGNAL(TIMESTAMP_MASTER_WR_T1, master_ts.ts100.t1, DATA16);
SIGNAL(TIMESTAMP_MASTER_WR_T2, master_ts.ts100.t2, DATA16);
SIGNAL(TIMESTAMP_MASTER_WR_T3, master_ts.ts100.t3, DATA16);
SIGNAL(TIMESTAMP_MASTER_WR_T4, master_ts.ts100.t4, DATA16);
SIGNAL(TIMESTAMP_MASTER_HI, master_ts.wr_multi.time_hi, DATA32);
SIGNAL(TIMESTAMP_MASTER_LO, master_ts.wr_multi.time_lo, DATA32);

// Pexaria Califa WR ts.
SIGNAL(TIMESTAMP_CALIFA_ID, califa.ts400.subsystem_id, DATA12);
SIGNAL(TIMESTAMP_CALIFA_WR_T1, califa.ts400.t1, DATA16);
SIGNAL(TIMESTAMP_CALIFA_WR_T2, califa.ts400.t2, DATA16);
SIGNAL(TIMESTAMP_CALIFA_WR_T3, califa.ts400.t3, DATA16);
SIGNAL(TIMESTAMP_CALIFA_WR_T4, califa.ts400.t4, DATA16);

// TRLO NeuLAND white rabbit ts.
SIGNAL(TIMESTAMP_NL_ID, neuland_ts.ts500.subsystem_id, DATA12);
SIGNAL(TIMESTAMP_NL_WR_T1, neuland_ts.ts500.t1, DATA16);
SIGNAL(TIMESTAMP_NL_WR_T2, neuland_ts.ts500.t2, DATA16);
SIGNAL(TIMESTAMP_NL_WR_T3, neuland_ts.ts500.t3, DATA16);
SIGNAL(TIMESTAMP_NL_WR_T4, neuland_ts.ts500.t4, DATA16);
