/** BEGIN_MIRROR_STRUCT ************************************************
 *
 * Mirror (1 to 1) structure.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_mirror_define.hh"

#ifndef USER_DEF_raw_event_U_QDC
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_U_QDC)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(CH);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(DATA32),STRUCT_MIRROR_TEMPLATE_ARG(DATA32),16> STRUCT_MIRROR_NAME(CH);
  STRUCT_MIRROR_FCNS_DECL(raw_event_U_QDC);
};
#endif//USER_DEF_raw_event_U_QDC

#ifndef USER_DEF_raw_event_U_TDC
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_U_TDC)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(CH);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(CH__i0,,32);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(CH[32]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_U_TDC);
};
#endif//USER_DEF_raw_event_U_TDC

#ifndef USER_DEF_raw_event_U_Sca
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_U_Sca)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(CH);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(CH__i0,,32);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(CH[32]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_U_Sca);
};
#endif//USER_DEF_raw_event_U_Sca

#ifndef USER_DEF_raw_event_U
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_U)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(QDC);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(QDC__i0,,4);
  STRUCT_MIRROR_TYPE(raw_event_U_QDC) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(QDC[4]);
  STRUCT_MIRROR_ITEM_CTRL(TDC);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(TDC__i0,,3);
  STRUCT_MIRROR_TYPE(raw_event_U_TDC) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TDC[3]);
  STRUCT_MIRROR_ITEM_CTRL(Sca);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(Sca__i0,,7);
  STRUCT_MIRROR_TYPE(raw_event_U_Sca) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(Sca[7]);
  STRUCT_MIRROR_ITEM_CTRL(MPflag);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(MPflag);
  STRUCT_MIRROR_ITEM_CTRL(Cyflag);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(Cyflag);
  STRUCT_MIRROR_ITEM_CTRL(ts);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ts);
  STRUCT_MIRROR_ITEM_CTRL(ro);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(ro);
  STRUCT_MIRROR_ITEM_CTRL(timeCH);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(timeCH__i0,,9);
  STRUCT_MIRROR_TYPE(DATA32) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(timeCH[9]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_U);
};
#endif//USER_DEF_raw_event_U

#ifndef USER_DEF_raw_event
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event) : public STRUCT_MIRROR_BASE(raw_event_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_event_base);
  STRUCT_MIRROR_ITEM_CTRL(U);
  STRUCT_MIRROR_TYPE(raw_event_U) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(U);
  STRUCT_MIRROR_FCNS_DECL(raw_event);
};
#endif//USER_DEF_raw_event

#ifndef USER_DEF_raw_sticky
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_sticky) : public STRUCT_MIRROR_BASE(raw_sticky_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_sticky_base);
  STRUCT_MIRROR_FCNS_DECL(raw_sticky);
};
#endif//USER_DEF_raw_sticky

#include "gen/default_mirror_undef.hh"


/** END_MIRROR_STRUCT *************************************************/
