/*********************************************************************
 *
 * This file is autogenerated by /u/land/fake_cvmfs/upexps/../ucesb/lu_common/make_acc_auto_def.sh
 *
 * Editing is useless.
 *
 *********************************************************************
 *
 * Input file:    /u/land/fake_cvmfs/upexps/../ucesb/acc_def/has_pthread_getname_np.h
 * Basename:      HAS_PTHREAD_GETNAME_NP
 * Compiler:      g++
 * Compiler args: -I. -DUNPACKERNAME=s327 -DUNPACKER_IS_s327 -I/u/land/fake_cvmfs/upexps/../ucesb/file_input -I/u/land/fake_cvmfs/upexps/../ucesb/file_input/lmd_struct -I/u/land/fake_cvmfs/upexps/../ucesb/threading -I/u/land/fake_cvmfs/upexps/../ucesb/lu_common -I/u/land/fake_cvmfs/upexps/../ucesb/acc_def -ansi -Wall -W -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wwrite-strings -Wconversion -g -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_LIMIT_MACROS -DHAVE_TEE -Igen_s327 -DGENDIR="gen_s327" -DUSE_EXT_WRITER= -DUSING_EXT_WRITER= -DEXT_WRITER_PREFIX="/u/land/fake_cvmfs/upexps/../ucesb/hbook/" -I/u/land/fake_cvmfs/upexps/../ucesb/hbook -DUSE_CURSES=1 -I/u/land/fake_cvmfs/upexps/../ucesb/watcher -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/u/land/fake_cvmfs/upexps/landdaq_/vidsel/cros3 -I/u/land/fake_cvmfs/upexps/../ucesb/dets/pdc -I/u/land/fake_cvmfs/upexps/landdaq_/vidsel/siderem -I/u/land/fake_cvmfs/upexps/../ucesb/dets/sst -DCONTROL_INCLUDE -DUSE_LOCAL_ERROR_HANDLING -I./../land_common -I/u/land/fake_cvmfs/upexps/landdaq/ccdaqlib -DUSE_CROS3_REWRITE -DUSE_DIAMOND_REWRITE -DUSER_STRUCT_FILE="s327_user_struct.hh" -I/u/land/fake_cvmfs/upexps/../ucesb/dets/sst -DHAVE_THREAD_LOCAL_STORAGE -pthread -DUSE_PTHREAD=1 -DHAVE_PTHREAD -DUSE_LMD_INPUT=1 -DUSE_LMD_OUTPUT_TCP -I/u/land/fake_cvmfs/upexps/../ucesb/mapcalib
 *
 ********************************************************************/

#ifndef __AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__
#define __AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__

/*
 * Option: pthread_h
 * Option: notavail
 */
/*
 * -DACC_DEF_HAS_PTHREAD_GETNAME_NP_pthread_h



 * --> exit 0 (len 0)
 */
/*
 * -DACC_DEF_HAS_PTHREAD_GETNAME_NP_notavail



 * --> exit 0 (len 0)
 */

/********************************************************************/

#define ACC_DEF_HAS_PTHREAD_GETNAME_NP_pthread_h 1

/********************************************************************/

#endif/*__AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__*/
