#########################################################
# Specify the name of the target executable

TARGETS:=s287

#########################################################
# Include common Makefile

include ../makefile_common.mk
