#########################################################
# Specify the name of the target executable

TARGETS:=tacquila17

#########################################################
# Include common Makefile

include ../makefile_common.mk
