#########################################################
# Specify the name of the target executable

TARGETS:=aida

#########################################################
# Include common Makefile

include ../makefile_common.mk
