#########################################################
# Specify the name of the target executable

TARGETS:=tamex_multi_pc_readout

#########################################################

CLEAN_TARGETS+=clean_mapping

#########################################################
# Include common Makefile

include ../makefile_common.mk

#########################################################
# Extra rules
clean_mapping:
	rm -rf mapping.h

