UCESB_BASE_DIR=../../unpacker

.PHONY: all
all:
	@$(MAKE) -C . -f $(UCESB_BASE_DIR)/makefile_unpacker.inc UNPACKER=tamex_multi_pc_readout UCESB_BASE_DIR=$(UCESB_BASE_DIR)

clean:
	@$(MAKE) -C . -f $(UCESB_BASE_DIR)/makefile_unpacker.inc UNPACKER=tamex_multi_pc_readout UCESB_BASE_DIR=$(UCESB_BASE_DIR) clean
