#########################################################
# Specify the name of the target executable

TARGETS:=uppsala

#########################################################
# Include common Makefile

include ../makefile_common.mk
