#########################################################
# Specify the name of the target executable

TARGETS:=s232

#########################################################
# Include common Makefile

include ../makefile_common.mk
