#########################################################
# Specify the name of the target executable

# Sub-unpacker information:
# run001 until run060: Fiber 1 and Fiber 4 are connected to clock TDC
# run061 until run068: Fiber 1 and Fiber 5 are connected to clock TDC
# run069 until run101: Fiber 1 and Fiber 6 are connected to clock TDC
# run001 until run085: Carbon beam
# run086 until run101: Proton beam

# Los detector is connected to tamex.los_0 and to tamex.ptof_0[17-32]

TARGETS:= kvi2018_001_060 kvi2018_061_068 kvi2018_069_101 kvi2018_086_101

#########################################################
# Include common Makefile

include ../makefile_common.mk
