#########################################################
# Specify the name of the target executable

TARGETS:=kvi2018

#########################################################
# Include common Makefile

include ../makefile_common.mk
