#include "mapping_los.hh"
#include "mapping_timestamp.hh"
#include "mapping_pspx_r3broot.hh"
#include "mapping_fiber.hh"
//#include "mapping_tofd.hh"
#include "mapping_ptof.hh"
//#include "mapping_fifilter.hh"
//#include "mapping_fitrace.hh"
//#include "mapping_fitest.hh"
//#include "mapping_fitrack.hh"
//#include "mapping_sipd.hh"
//#include "mapping_strawtubes.hh"

