#########################################################
# Specify the name of the target executable

TARGETS:=dec2006

#########################################################
# Include common Makefile

include ../makefile_common.mk
