/** BEGIN_MIRROR_STRUCT ************************************************
 *
 * Mirror (1 to 1) structure.
 *
 * Do not edit - automatically generated.
 */

#include "gen/default_mirror_define.hh"

#ifndef USER_DEF_raw_event_TPC
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_TPC)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(DT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(DT__i0,,4);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(DT[4]);
  STRUCT_MIRROR_ITEM_CTRL(LT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(LT__i0,,2);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(LT[2]);
  STRUCT_MIRROR_ITEM_CTRL(RT);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(RT__i0,,2);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(RT[2]);
  STRUCT_MIRROR_ITEM_CTRL(A);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(A__i0,,4);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(A[4]);
  STRUCT_MIRROR_ITEM_CTRL(AL);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(AL__i0,,2);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(AL[2]);
  STRUCT_MIRROR_ITEM_CTRL(AR);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(AR__i0,,2);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(AR[2]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_TPC);
};
#endif//USER_DEF_raw_event_TPC

#ifndef USER_DEF_raw_event_MUS
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_MUS)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(A);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(A__i0,,8);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(A[8]);
  STRUCT_MIRROR_FCNS_DECL(raw_event_MUS);
};
#endif//USER_DEF_raw_event_MUS

#ifndef USER_DEF_raw_event_SST
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event_SST)
{
public:
  STRUCT_MIRROR_ITEM_CTRL(E);
  STRUCT_MIRROR_TYPE(DATA12) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(E);
  STRUCT_MIRROR_FCNS_DECL(raw_event_SST);
};
#endif//USER_DEF_raw_event_SST

#ifndef USER_DEF_raw_event
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_event) : public STRUCT_MIRROR_BASE(raw_event_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_event_base);
  STRUCT_MIRROR_ITEM_CTRL(TPC);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(TPC__i0,,6);
  STRUCT_MIRROR_TYPE(raw_event_TPC) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(TPC[6]);
  STRUCT_MIRROR_ITEM_CTRL(MUS);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(MUS__i0,,3);
  STRUCT_MIRROR_TYPE(raw_event_MUS) STRUCT_MIRROR_TYPE_TEMPLATE_FULL STRUCT_MIRROR_NAME(MUS[3]);
  STRUCT_MIRROR_ITEM_CTRL(SST);
  STRUCT_MIRROR_ITEM_CTRL_ARRAY(SST__i0,,3);
  STRUCT_MIRROR_TYPE(raw_array_zero_suppress) < STRUCT_MIRROR_TYPE_TEMPLATE STRUCT_MIRROR_TEMPLATE_ARG(raw_event_SST),STRUCT_MIRROR_TEMPLATE_ARG(raw_event_SST),1024> STRUCT_MIRROR_NAME(SST[3]);
  STRUCT_MIRROR_FCNS_DECL(raw_event);
};
#endif//USER_DEF_raw_event

#ifndef USER_DEF_raw_sticky
STRUCT_MIRROR_TEMPLATE
class STRUCT_MIRROR_STRUCT(raw_sticky) : public STRUCT_MIRROR_BASE(raw_sticky_base)
{
public:
  STRUCT_MIRROR_ITEM_CTRL_BASE(raw_sticky_base);
  STRUCT_MIRROR_FCNS_DECL(raw_sticky);
};
#endif//USER_DEF_raw_sticky

#include "gen/default_mirror_undef.hh"


/** END_MIRROR_STRUCT *************************************************/
